package eu.wohlben.qits.cli.bootstrap.platform;

import java.util.Map;

/**
 * The seed stack and qits-platform-deployments' run-args, generated. Both are ports of the
 * heredocs in {@code qits-local-up.sh}, comments and all: the comments are where the reasons live,
 * and a generated file nobody can read is a file nobody can fix.
 */
public final class ComposeTemplate {

    private ComposeTemplate() {
    }

    public static String compose(Map<String, String> values) {
        return Tokens.apply(COMPOSE, values);
    }

    public static String runArgs(Map<String, String> values) {
        return Tokens.apply(RUN_ARGS, values);
    }

    private static final String COMPOSE = """
            # Generated by qits-cli-bootstrap — the SEED of the local qits platform: only the services that
            # build and deploy the rest. Everything else (observability, stt, projects, workspaces, events) is
            # deployed by qits-platform-deployments through the main pipeline and is deliberately NOT in this
            # file — look for it in `docker ps` under qits-pd-${ENV_NAME}-qits-* container names
            # (qits-pd-platform-qits-* for the platform services), redeployed on every green push.
            #
            # Manage with: docker compose -p qits -f ${COMPOSE_FILE} ps|logs -f|down
            # (compose down leaves deployed containers running; remove those via the deployer's API or docker.)

            name: qits

            networks:
              qits-net:
                # The one shared network: seed services, deployed applications and ci step containers all
                # join it and resolve each other by alias. It is the deployer's
                # qits.platform.deployments.legacy-network, which every container it starts also joins while
                # the platform still holds direct cross-application URLs. External because the bootstrap (or a previous stack, or qits-ci's
                # own boot) may have created it already — compose refuses to adopt a network it did not
                # label.
                name: qits-net
                external: true

            volumes:
              # qits-artifacts' store: blobs, packages and the git host's repositories — which are blobs too
              # now, so the git host needs no volume of its own. Explicitly named: the deployer's run-args
              # reference these volumes by name.
              qits-artifacts-data:
                name: qits-artifacts-data
              qits-ci-data:
                name: qits-ci-data
              # THE PLATFORM'S TOPOLOGY AND ITS DEPLOYMENT HISTORY LIVE HERE — every environment, every
              # service, every link, every deployment row and the rollback pins read off them. One database
              # for one component; the image refuses to boot without the url that points at this volume,
              # because a redeploy onto ephemeral storage would come up healthy and empty and then reconcile
              # every environment against an empty catalogue.
              qits-platform-deployments-data:
                name: qits-platform-deployments-data
              # THE SIGNING KEY LIVES HERE. An idp on ephemeral storage comes up healthy and mints a new
              # keypair on every recreate, invalidating every token in flight with nothing in any log to say
              # why — which is why its image refuses to boot without the url that points at this volume.
              qits-idp-data:
                name: qits-idp-data
              # Mounted by DEPLOYED containers via qits.platform.deployments.run-args, not by any service
              # below.
              qits-projects-data:
                name: qits-projects-data
              qits-workspaces-data:
                name: qits-workspaces-data
              qits-stt-data:
                name: qits-stt-data
              qits-events-data:
                name: qits-events-data
              # The deployer's run-args config (config/application.properties, written by the bootstrap). A
              # volume rather than env so a self-update's successor inherits it — env cannot nest these
              # values.
              qits-platform-deployments-config:
                name: qits-platform-deployments-config

            services:
              # The issuer. No published host port and no gateway route: in phase 1 nothing outside qits-net
              # talks to it, and /idp/token reachable from the host through an unauthenticated gateway would be
              # a token vending machine. Phase 3's user flows are what put it on the route table.
              #
              # First in this file because it is first in the order that matters: every service below mints or
              # validates against it, and the git host's very first post-receive needs a token.
              qits-idp:
                image: qits/idp:latest
                container_name: qits-idp
                environment:
                  # Not a default the image could ship: the signing key lands in this database, and the image
                  # refuses to boot rather than write it into a container layer.
                  QUARKUS_DATASOURCE_IDP_JDBC_URL: jdbc:h2:file:/data/idp/h2/idp
                  # The 'iss' of every token and the base of every endpoint the discovery document advertises.
                  # Spelled here although it equals the shipped default, for the reason every other address in
                  # this file is spelled: an address a deployment inherits silently is one nobody knows to
                  # change. Consumers below carry the same string; a mismatch is rejected at validation.
                  QITS_IDP_ISSUER: ${IDP}
                  # Generated by this bootstrap, recorded in .qits-bootstrap.env, and handed to the matching
                  # service below. A client without a secret is refused, never open.
                  QITS_IDP_CLIENT_QITS_CI_SECRET: "${IDP_SECRET_QITS_CI}"
                  QITS_IDP_CLIENT_QITS_CD_SECRET: "${IDP_SECRET_QITS_CD}"
                  QITS_IDP_CLIENT_QITS_ARTIFACTS_SECRET: "${IDP_SECRET_QITS_ARTIFACTS}"
                  # Unused in phase 1 (qits-workspaces' agents are phase 2, the gateway's user flows phase 3).
                  # Seeded anyway: the cost is a config line, and the cost of the omission is invalid_client on
                  # a path nobody was looking at.
                  QITS_IDP_CLIENT_QITS_WORKSPACES_SECRET: "${IDP_SECRET_QITS_WORKSPACES}"
                  QITS_IDP_CLIENT_QITS_GATEWAY_SECRET: "${IDP_SECRET_QITS_GATEWAY}"
                  # qits-platform-deployments is not on the idp's shipped audience lists — it postdates them —
                  # and an audience a client may not ask for is invalid_target, not a silent bare call. qits-ci
                  # is the one client that writes to it (the build-succeeded intake), and this bootstrap
                  # borrows that client for the events it replays by hand, so its list is the one restated
                  # here. The deployer itself needs no client and no list: it mints nothing, it only validates
                  # what qits-ci presents.
                  QITS_IDP_CLIENT_QITS_CI_AUDIENCES: "${IDP_AUDIENCES}"
                  # The one claim grant phase 1 needs. The git host announces every push to ci's intake, which
                  # checks the token's project claim against the repo the event names — and the git host speaks
                  # for ALL repos, so its grant is the wildcard. The idp only states the claim; qits-ci's own
                  # enforcement is what reads '*' as covering every value.
                  QITS_IDP_CLIENT_QITS_ARTIFACTS_CLAIMS_PROJECT: "*"
                volumes:
                  - qits-idp-data:/data
                networks: [qits-net]
                restart: unless-stopped

              # The deployer, and the topology it decides from: one component, one database, one docker
              # socket. It is the merge-back of qits-cd and qits-serviceregistry, so it stands where both
              # used to. In the seed because the 'dev' environment is created through it minutes from now and
              # because nothing else can start a container. No published host port of its own — the gateway's
              # /platform-deployments route is the door. Ready at /platform-deployments/q/health/ready.
              qits-platform-deployments:
                image: qits/platform-deployments:latest
                container_name: qits-platform-deployments
                group_add: ["${DOCKER_GID}"]
                environment:
                  # Same reason as the idp's twin above: the shipped default sits under ${user.home}, which
                  # this image's passwd-less UID 1001 has not got, so the binary dies at Flyway rather than
                  # writing the platform's topology into a container layer.
                  QUARKUS_DATASOURCE_PLATFORMDEPLOYMENTS_JDBC_URL: jdbc:h2:file:/data/platformdeployments/h2/platformdeployments
                  # It pulls through the HOST daemon — same reasoning as ci's registry host.
                  QITS_ARTIFACTS_REGISTRY_HOST: localhost:${REGISTRY_PORT}
                  # Per-application run-args live in the qits-platform-deployments-config volume
                  # (config/application.properties, written by the bootstrap), NOT here: a self-update's
                  # successor must inherit them, and env cannot nest those values.
                  # Machine auth, INBOUND ONLY. The build-succeeded intake and the topology writes demand a
                  # bearer addressed to qits-platform-deployments; every read stays open. There is no
                  # oidc-client and no secret — the merge removed the peer its ancestor authenticated to.
                  QITS_AUTH_MACHINE_REQUIRED: "${MACHINE_REQUIRED}"
                  QUARKUS_OIDC_AUTH_SERVER_URL: ${IDP}
                volumes:
                  - qits-platform-deployments-data:/data
                  - qits-platform-deployments-config:/work/config
                  - /var/run/docker.sock:/var/run/docker.sock
                networks: [qits-net]
                restart: unless-stopped

              qits-gateway:
                image: qits/gateway:latest
                container_name: qits-gateway
                ports:
                  - "${PORT}:8080"
                environment:
                  # The route table: an entry is both the on-switch and the target. Aliases of the
                  # pipeline-deployed services resolve the moment the deployer cuts them over; until then
                  # those routes 502.
                  QITS_GATEWAY_PROXY_HOSTS_ARTIFACTS: qits-artifacts   # also claims root-level /v2 (OCI registry)
                  QITS_GATEWAY_PROXY_HOSTS_CI: qits-ci
                  QITS_GATEWAY_PROXY_HOSTS_PLATFORM_DEPLOYMENTS: qits-platform-deployments
                  QITS_GATEWAY_PROXY_HOSTS_OBSERVABILITY: qits-observability
                  QITS_GATEWAY_PROXY_HOSTS_PROJECTS: qits-projects
                  QITS_GATEWAY_PROXY_HOSTS_WORKSPACES: qits-workspaces
                  QITS_GATEWAY_PROXY_HOSTS_STT: qits-stt
                  QITS_GATEWAY_PROXY_HOSTS_EVENTS: qits-events
                networks: [qits-net]
                # No depends_on: on later runs compose starts only the services the deployer does not already
                # manage, and a dependency would resurrect a compose sibling next to its deployed replacement.
                restart: unless-stopped

              qits-artifacts:
                image: qits/artifacts:latest
                container_name: qits-artifacts
                ports:
                  # For the HOST daemon only: ci publish steps push and the deployer pulls through the host's
                  # docker daemon, which cannot resolve qits-net aliases. localhost:${REGISTRY_PORT} is in
                  # docker's default insecure list, so plain HTTP needs no daemon config. It is also this
                  # CLI's own door: the bootstrap runs on the host now, not as a container on qits-net.
                  - "127.0.0.1:${REGISTRY_PORT}:8080"
                environment:
                  QUARKUS_DATASOURCE_ARTIFACTS_JDBC_URL: jdbc:h2:file:/data/artifacts/h2/artifacts
                  QITS_ARTIFACTS_BLOBS_DIR: /data/artifacts/blobs
                  # Where the git host's post-receive hook delivers. Fire-and-forget: wrong host = CI
                  # silently never runs.
                  QITS_CI_INTAKE_URL: http://qits-ci:8080/ci/api/events/post-receive
                  # The default branch's escape hatch: a push carrying -o qits.token=<this> is let through
                  # even when protection is on. Unset would mean no value matches and nothing overrides —
                  # which is the shipped default everywhere else, and which this bootstrap cannot live with
                  # (it pushes main many times before a release endpoint exists to go through).
                  QITS_REPOSITORIES_GIT_PUSH_TOKEN: "${PUSH_TOKEN}"
                  # Protection stays ON here too: the bootstrap's own pushes carry the token above, and a
                  # rerun that silently disarmed the seatbelt would be the quiet failure.
                  QITS_REPOSITORIES_GIT_PROTECT_DEFAULT_BRANCH: "true"
                  # Machine auth. Inbound: the admin writes under /artifacts/api demand a bearer addressed to
                  # qits-artifacts. Outbound: the git host's post-receive announcement to qits-ci carries one.
                  QITS_AUTH_MACHINE_REQUIRED: "${MACHINE_REQUIRED}"
                  QUARKUS_OIDC_AUTH_SERVER_URL: ${IDP}
                  # The outbound switch, and the secret it must never travel without. qits-artifacts names the
                  # secret QITS_ARTIFACTS_CLIENT_SECRET in its own application.properties — the canonical
                  # QUARKUS_OIDC_CLIENT_CREDENTIALS_SECRET would override it too, but one spelling is enough
                  # and the file's own is the one that documents itself.
                  QUARKUS_OIDC_CLIENT_CLIENT_ENABLED: "${MACHINE_CLIENT}"
                  QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL: ${IDP}
                  QITS_ARTIFACTS_CLIENT_SECRET: "${IDP_SECRET_QITS_ARTIFACTS}"
                volumes:
                  - qits-artifacts-data:/data
                networks: [qits-net]
                restart: unless-stopped

              qits-ci:
                image: qits/ci:latest
                container_name: qits-ci
                # Unprivileged uid stays; the socket group is all it needs.
                group_add: ["${DOCKER_GID}"]
                environment:
                  QUARKUS_DATASOURCE_CI_JDBC_URL: "jdbc:h2:file:/data/ci/h2/ci;DB_CLOSE_DELAY=-1"
                  # The eventstream library (the outbox) owns its own datasource, whose shipped default sits
                  # under ${user.home} — which a container has not got, so H2 refuses the url at Flyway and the
                  # binary dies at boot. Every deployment of ci must spell this twin; so must the seed.
                  QUARKUS_DATASOURCE_EVENTSTREAM_JDBC_URL: jdbc:h2:file:/data/eventstream/h2/eventstream
                  # ci's own fetch of the pushed ref, and the same base as seen from inside a step
                  # container — steps join qits-net, so both resolve the git host directly.
                  QITS_CI_GIT_HOST_URL: http://qits-artifacts:8080/artifacts
                  QITS_CI_CONTAINER_GIT_URL: http://qits-artifacts:8080/artifacts
                  QITS_CI_NETWORK: qits-net
                  # Where a green build is announced. Fire-and-forget and swallowed at debug, so a wrong
                  # value here deploys nothing and says nothing — which is exactly why it is spelled rather
                  # than inherited. The key is qits.platform.deployments.intake-url; the
                  # qits.cd.intake-url it replaced is gone rather than aliased.
                  QITS_PLATFORM_DEPLOYMENTS_INTAKE_URL: http://qits-platform-deployments:8080/platform-deployments/api/events/build-succeeded
                  # Injected into publish steps as QITS_REGISTRY: dialled by the HOST daemon (see the
                  # qits-artifacts ports note).
                  QITS_ARTIFACTS_REGISTRY_HOST: localhost:${REGISTRY_PORT}
                  # The npm roots (QITS_NPM_REGISTRY_URL / QITS_NPM_PROXY_URL) are deliberately NOT overridden
                  # here: a step container dials THOSE itself, on qits-net, so ci's shipped defaults are
                  # already right. Copying the localhost mapping above onto them would point every npm install
                  # at the step container's own loopback.
                  # The binary every step container downloads and execs — uploaded by this bootstrap, digest
                  # pinned. Blank would mean every run fails as never-registered.
                  QITS_CI_DAEMON_VERSION: "${DAEMON_SHA}"
                  # Machine auth. Inbound: /ci/api/events/* demands a bearer addressed to qits-ci whose project
                  # claim covers the event's repo. Outbound: the build-succeeded notify to
                  # qits-platform-deployments carries one.
                  QITS_AUTH_MACHINE_REQUIRED: "${MACHINE_REQUIRED}"
                  QUARKUS_OIDC_AUTH_SERVER_URL: ${IDP}
                  QUARKUS_OIDC_CLIENT_CLIENT_ENABLED: "${MACHINE_CLIENT}"
                  QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL: ${IDP}
                  QUARKUS_OIDC_CLIENT_CREDENTIALS_SECRET: "${IDP_SECRET_QITS_CI}"
                volumes:
                  - qits-ci-data:/data
                  - /var/run/docker.sock:/var/run/docker.sock
                networks: [qits-net]
                restart: unless-stopped
            """;

    private static final String RUN_ARGS = """
            # Generated by qits-cli-bootstrap — qits.platform.deployments.run-args.<application>: what each deployed container
            # needs beyond its image. Whitespace-split, appended verbatim between the deployer's flags and the
            # image. The namespace was qits.cd.run-args before the merge-back; a deployment carrying the old
            # spelling configures nothing.
            qits.platform.deployments.run-args.qits-gateway=-p ${PORT}:8080 -e QITS_GATEWAY_PROXY_HOSTS_ARTIFACTS=qits-artifacts -e QITS_GATEWAY_PROXY_HOSTS_CI=qits-ci -e QITS_GATEWAY_PROXY_HOSTS_PLATFORM_DEPLOYMENTS=qits-platform-deployments -e QITS_GATEWAY_PROXY_HOSTS_OBSERVABILITY=qits-observability -e QITS_GATEWAY_PROXY_HOSTS_PROJECTS=qits-projects -e QITS_GATEWAY_PROXY_HOSTS_WORKSPACES=qits-workspaces -e QITS_GATEWAY_PROXY_HOSTS_STT=qits-stt -e QITS_GATEWAY_PROXY_HOSTS_EVENTS=qits-events
            # The push token rides here so it is already in place when the default branch's protection is
            # switched on: turning protection on is then one property on the artifacts side, not a two-part
            # change that could leave a running platform locked out of its own bootstrap.
            qits.platform.deployments.run-args.qits-artifacts=-p 127.0.0.1:${REGISTRY_PORT}:8080 -v qits-artifacts-data:/data -e QUARKUS_DATASOURCE_ARTIFACTS_JDBC_URL=jdbc:h2:file:/data/artifacts/h2/artifacts -e QITS_ARTIFACTS_BLOBS_DIR=/data/artifacts/blobs -e QITS_CI_INTAKE_URL=http://qits-ci:8080/ci/api/events/post-receive -e QITS_REPOSITORIES_GIT_PUSH_TOKEN=${PUSH_TOKEN} -e QITS_REPOSITORIES_GIT_PROTECT_DEFAULT_BRANCH=true -e QITS_AUTH_MACHINE_REQUIRED=${MACHINE_REQUIRED} -e QUARKUS_OIDC_AUTH_SERVER_URL=${IDP} -e QUARKUS_OIDC_CLIENT_CLIENT_ENABLED=${MACHINE_CLIENT} -e QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL=${IDP} -e QITS_ARTIFACTS_CLIENT_SECRET=${IDP_SECRET_QITS_ARTIFACTS}
            # QITS_PLATFORM_DEPLOYMENTS_INTAKE_URL is where a green build is announced. It equals ci's own shipped default and
            # is spelled anyway: the notify is fire-and-forget and swallowed at debug, so a wrong value
            # deploys nothing and reports nothing.
            qits.platform.deployments.run-args.qits-ci=-v qits-ci-data:/data -v /var/run/docker.sock:/var/run/docker.sock --group-add ${DOCKER_GID} -e QUARKUS_DATASOURCE_CI_JDBC_URL=jdbc:h2:file:/data/ci/h2/ci;DB_CLOSE_DELAY=-1 -e QUARKUS_DATASOURCE_EVENTSTREAM_JDBC_URL=jdbc:h2:file:/data/eventstream/h2/eventstream -e QITS_CI_GIT_HOST_URL=http://qits-artifacts:8080/artifacts -e QITS_CI_CONTAINER_GIT_URL=http://qits-artifacts:8080/artifacts -e QITS_CI_NETWORK=qits-net -e QITS_PLATFORM_DEPLOYMENTS_INTAKE_URL=http://qits-platform-deployments:8080/platform-deployments/api/events/build-succeeded -e QITS_ARTIFACTS_REGISTRY_HOST=localhost:${REGISTRY_PORT} -e QITS_CI_DAEMON_VERSION=${DAEMON_SHA} -e QITS_EVENTS_URL=http://qits-events:8080 -e QITS_AUTH_MACHINE_REQUIRED=${MACHINE_REQUIRED} -e QUARKUS_OIDC_AUTH_SERVER_URL=${IDP} -e QUARKUS_OIDC_CLIENT_CLIENT_ENABLED=${MACHINE_CLIENT} -e QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL=${IDP} -e QUARKUS_OIDC_CLIENT_CREDENTIALS_SECRET=${IDP_SECRET_QITS_CI}
            # The deployer's own deployment — the self-update handoff. Three mounts, all load-bearing: the
            # data volume holds the topology AND the deployment history, the config volume holds this very
            # file so the successor inherits every line of it, and the docker socket is what makes it a
            # deployer at all. Machine auth INBOUND only: it validates qits-ci's bearer and mints nothing, so
            # no oidc-client and no secret.
            qits.platform.deployments.run-args.qits-platform-deployments=-v qits-platform-deployments-data:/data -v qits-platform-deployments-config:/work/config -v /var/run/docker.sock:/var/run/docker.sock --group-add ${DOCKER_GID} -e QUARKUS_DATASOURCE_PLATFORMDEPLOYMENTS_JDBC_URL=jdbc:h2:file:/data/platformdeployments/h2/platformdeployments -e QITS_ARTIFACTS_REGISTRY_HOST=localhost:${REGISTRY_PORT} -e QITS_AUTH_MACHINE_REQUIRED=${MACHINE_REQUIRED} -e QUARKUS_OIDC_AUTH_SERVER_URL=${IDP}
            # The idp's own deployment. The volume is the whole point: the signing key is in that database, and
            # a redeploy that lands on a fresh one invalidates every token in flight. The claims grant is the
            # git host's wildcard — it announces pushes for every repo, so its project claim covers every value.
            # The audience line is the deployer's admission ticket: qits-platform-deployments postdates the
            # idp's shipped lists, and qits-ci asking for an audience it may not have is invalid_target.
            # Restated in full, because the key replaces the list rather than extending it.
            qits.platform.deployments.run-args.qits-idp=-v qits-idp-data:/data -e QUARKUS_DATASOURCE_IDP_JDBC_URL=jdbc:h2:file:/data/idp/h2/idp -e QITS_IDP_ISSUER=${IDP} -e QITS_IDP_CLIENT_QITS_CI_SECRET=${IDP_SECRET_QITS_CI} -e QITS_IDP_CLIENT_QITS_CD_SECRET=${IDP_SECRET_QITS_CD} -e QITS_IDP_CLIENT_QITS_ARTIFACTS_SECRET=${IDP_SECRET_QITS_ARTIFACTS} -e QITS_IDP_CLIENT_QITS_WORKSPACES_SECRET=${IDP_SECRET_QITS_WORKSPACES} -e QITS_IDP_CLIENT_QITS_GATEWAY_SECRET=${IDP_SECRET_QITS_GATEWAY} -e QITS_IDP_CLIENT_QITS_CI_AUDIENCES=${IDP_AUDIENCES} -e QITS_IDP_CLIENT_QITS_ARTIFACTS_CLAIMS_PROJECT=*
            qits.platform.deployments.run-args.qits-stt=-v qits-stt-data:/data -e QITS_SPEECH_HOME=/data/speech
            # projects no longer mounts the shared repositories volume at all — it clones its own git mirrors
            # over the wire, through qits.artifacts.url, into its own data dir. QITS_PROJECTS_DATA_DIR is
            # spelled here rather than left to the image default (${user.home}/...), which resolves to the
            # literal "?" under this image's passwd-less UID 1001 — the same reason the datasource URLs are
            # spelled. QITS_ARTIFACTS_URL already equals the service's own shipped default; it is spelled
            # anyway, because an address a deployment inherits silently is an address nobody knows to change.
            #
            # QITS_REPOSITORIES_GIT_PUSH_TOKEN is the SAME token qits-artifacts' hook checks, one line above.
            # projects advances refs on the git host by pushing now, and the default branch is protected here,
            # so without the token every pull that fast-forwards main is refused. A branch delete deliberately
            # sends no token.
            qits.platform.deployments.run-args.qits-projects=-v qits-projects-data:/data -e QUARKUS_DATASOURCE_PROJECTS_JDBC_URL=jdbc:h2:file:/data/projects/h2/projects -e QUARKUS_DATASOURCE_EPICS_JDBC_URL=jdbc:h2:file:/data/epics/h2/epics -e QITS_PROJECTS_DATA_DIR=/data/mirrors -e QITS_ARTIFACTS_URL=http://qits-artifacts:8080 -e QITS_REPOSITORIES_GIT_PUSH_TOKEN=${PUSH_TOKEN}
            # QITS_ARTIFACTS_URL is where release PUSHES the release commit — the git host, over HTTP, so
            # the ordinary post-receive fires and the ordinary pipeline builds it.
            # The eventstream twin (same pair qits-ci carries above): a release publishes SoftwareRelease
            # through the shared bus client, whose outbox owns its own datasource. QITS_EVENTS_URL is where
            # the outbox drains to.
            # QITS_WORKSPACE_GIT_HOST (qits.workspace.git-host) is the address a WORKSPACE container uses to
            # reach this platform — git clone/push, OTLP, the agent's MCP servers and the daemon control
            # socket are all composed as http://<this>:8080/... It must be spelled, because the sentinel
            # "auto" is wrong on this topology and wrong silently: auto detects WSL2 and answers the primary
            # LAN IPv4, which is the address of the machine when qits runs ON the host — but qits-workspaces
            # runs in a container here, so what it measures is its OWN container's address and every
            # container->platform URL 404s. qits-gateway, not qits-workspaces or qits-artifacts: it is the one
            # name on qits-net that fronts the WHOLE platform.
            qits.platform.deployments.run-args.qits-workspaces=-v qits-workspaces-data:/data -v /var/run/docker.sock:/var/run/docker.sock --group-add ${DOCKER_GID} -e QUARKUS_DATASOURCE_WORKSPACES_JDBC_URL=jdbc:h2:file:/data/workspaces/h2/workspaces -e QUARKUS_DATASOURCE_EVENTSTREAM_JDBC_URL=jdbc:h2:file:/data/eventstream/h2/eventstream -e QITS_PROJECTS_URL=http://qits-projects:8080 -e QITS_ARTIFACTS_URL=http://qits-artifacts:8080 -e QITS_EVENTS_URL=http://qits-events:8080 -e QITS_WORKSPACE_GIT_HOST=qits-gateway
            qits.platform.deployments.run-args.qits-events=-v qits-events-data:/data -e QUARKUS_DATASOURCE_EVENTS_JDBC_URL=jdbc:h2:file:/data/events/h2/events
            """;
}
