package eu.wohlben.qits.cli.bootstrap.platform;

import java.util.Map;

/**
 * The seed stack and qits-deployments' run-args, generated. Both are ports of the heredocs in
 * {@code qits-local-up.sh}, comments and all: the comments are where the reasons live, and a
 * generated file nobody can read is a file nobody can fix.
 * <p>
 * <b>Every service below is keyed and named by its WIRE ALIAS</b> — {@code prod-qits-ci} for an
 * environment service, {@code qits-platform-idp} for a platform one, exactly what
 * {@link PlatformModel#wireAlias} derives and exactly what the deployer will give the container
 * that replaces it. A container's own name resolves on a user-defined network the way an alias
 * does, so naming the seed after the alias is what makes the addresses in this very file — and in
 * the run-args beside it — right from the first second rather than from the first cutover. It is
 * also how the deployer finds its predecessor: it searches the qualified alias AND the bare
 * application name, so a seed under either spelling is adopted rather than left running beside its
 * replacement.
 */
public final class ComposeTemplate {

    private ComposeTemplate() {
    }

    public static String compose(Map<String, String> values) {
        return Tokens.apply(COMPOSE, values);
    }

    public static String runArgs(Map<String, String> values) {
        return Tokens.apply(RUN_ARGS, values);
    }

    private static final String COMPOSE = """
            # Generated by qits-cli-bootstrap — the SEED of the local qits platform: only the services that
            # build and deploy the rest. Everything else (observability, stt, projects, workspaces, events) is
            # deployed by qits-deployments through the main pipeline and is deliberately NOT in this file —
            # look for it in `docker ps` under qits-pd-${ENV_NAME}-qits-* container names (qits-pd-qits-* for
            # the four platform services), redeployed on every green push.
            #
            # Manage with: docker compose -p qits -f ${COMPOSE_FILE} ps|logs -f|down
            # (compose down leaves deployed containers running; remove those via the deployer's API or docker.)

            name: qits

            networks:
              qits-net:
                # The one shared network: seed services, deployed applications and ci step containers all
                # join it and resolve each other by alias. It is the deployer's
                # qits.platform.deployments.legacy-network, which every container it starts also joins while
                # the platform still holds direct cross-application URLs. External because the bootstrap (or a previous stack, or qits-ci's
                # own boot) may have created it already — compose refuses to adopt a network it did not
                # label.
                name: qits-net
                external: true

            volumes:
              # Every volume is keyed by the APPLICATION it belongs to, because the deployer's run-args
              # reference them by name and an application's run-args are looked up by that same name.
              #
              # THERE IS NO VOLUME PER DATABASE ANY MORE. Six services kept a file H2 under /data and
              # moved to the postgres below: the deployer, qits-ci (twice), qits-platform-idp,
              # qits-projects, qits-workspaces and qits-events. Where /data held the H2 and nothing else
              # — ci, the idp, events, the deployer — the volume is gone with it and the images have no
              # mount point left to give it. Where /data holds files as well, the volume stays and only
              # the datasource left it.
              #
              # qits-platform-artifacts' store: blobs, packages and the git host's repositories — which are
              # blobs too now, so the git host needs no volume of its own. It is the one service still on
              # a file H2, and its /data carries both.
              qits-platform-artifacts-data:
                name: qits-platform-artifacts-data
              # THE PLATFORM'S TOPOLOGY, ITS DEPLOYMENT HISTORY AND EVERY DATABASE THIS PLATFORM RUNS
              # LIVE HERE — every environment, every service, every link, every deployment row and the
              # rollback pins read off them, the credentials of every database the deployer provisions,
              # and the idp's signing key. An idp on ephemeral storage comes up healthy and mints a new
              # keypair on every recreate, invalidating every token in flight with nothing in any log to
              # say why; that is now this volume's problem to prevent rather than one of its own.
              #
              # THE MOUNT PATH IS /var/lib/postgresql AND NOT /var/lib/postgresql/data. postgres 18 puts
              # PGDATA at /var/lib/postgresql/18/docker, so a volume mounted at the old data path is
              # mounted beside the cluster rather than over it: everything works, everything is fast, and
              # every byte is written into the container's own layer and lost on the next recreate.
              qits-oci-postgresql-data:
                name: qits-oci-postgresql-data
              # Mounted by DEPLOYED containers via qits.platform.deployments.run-args, not by any service
              # below. Each one holds FILES that no database replaced: qits-projects' git mirrors and the
              # credentials beside them, qits-workspaces' per-repository trees, qits-stt's models.
              qits-projects-data:
                name: qits-projects-data
              qits-workspaces-data:
                name: qits-workspaces-data
              qits-stt-data:
                name: qits-stt-data
              # The deployer's run-args config (config/application.properties, written by the bootstrap). A
              # volume rather than env so a self-update's successor inherits it — env cannot nest these
              # values.
              qits-deployments-config:
                name: qits-deployments-config${LETSENCRYPT_VOLUME}

            # Each key below is the service's WIRE ALIAS, and so is its container_name: a container's own
            # name resolves on this network exactly as an alias does, so the seed answers to the address
            # every run-arg in the generated properties file already carries. An environment service is
            # ${ENV_NAME}-qits-<app>; a platform service is its bare repository name, which says the plane
            # itself.
            services:
              # The issuer. No published host port and no gateway route: in phase 1 nothing outside qits-net
              # talks to it, and /idp/token reachable from the host through an unauthenticated gateway would be
              # a token vending machine. Phase 3's user flows are what put it on the route table.
              #
              # First in this file because it is first in the order that matters: every service below mints or
              # validates against it, and the git host's very first post-receive needs a token.
              qits-platform-idp:
                image: qits/platform-idp:latest
                container_name: qits-platform-idp
                environment:
                  # THE STORE, and the signing key is in it: an idp that comes up on an empty database
                  # mints a new keypair and invalidates every token in flight, with nothing in any log to
                  # say why. The image ships no default for these three and refuses to boot without them.
                  #
                  # SPELLED HERE, AND ONLY HERE. This container is started by compose before any deployer
                  # exists, so the bootstrap creates the role and the database over JDBC and hands the
                  # credential over itself. Every deployment after this one gets the same three variables
                  # from qits-platform-deployments, which reads `resources: postgresql:db` in this
                  # repository's deployments.yml — which is why the run-args line beside this file carries
                  # no datasource env at all.
                  QITS_RESOURCE_DB_URL: jdbc:postgresql://${ENV_NAME}-qits-oci-postgresql:5432/qits_platform_idp
                  QITS_RESOURCE_DB_USERNAME: qits_platform_idp
                  QITS_RESOURCE_DB_PASSWORD: "${PG_PLATFORM_IDP_PASSWORD}"
                  # The 'iss' of every token and the base of every endpoint the discovery document advertises.
                  # Spelled here although it equals the shipped default, for the reason every other address in
                  # this file is spelled: an address a deployment inherits silently is one nobody knows to
                  # change. Consumers below carry the same string; a mismatch is rejected at validation.
                  QITS_IDP_ISSUER: ${IDP}
                  # WHICH CLIENTS EXIST. The key REPLACES the shipped list rather than extending it, and an
                  # id that is not on it is unknown — invalid_client, with nothing to say it was a typo. It is
                  # spelled because a client id is a wire alias now, so it moves with the environment name.
                  QITS_IDP_CLIENTS: "${IDP_CLIENTS}"
                  # Generated by this bootstrap, recorded in .qits-bootstrap.env, and handed to the matching
                  # service below. A client without a secret is refused, never open.
                  QITS_IDP_CLIENT_${ENV_KEY}_QITS_CI_SECRET: "${IDP_SECRET_CI}"
                  QITS_IDP_CLIENT_QITS_PLATFORM_ARTIFACTS_SECRET: "${IDP_SECRET_PLATFORM_ARTIFACTS}"
                  # Unused in phase 1 (qits-workspaces' agents are phase 2, the gateway's user flows phase 3).
                  # Seeded anyway: the cost is a config line, and the cost of the omission is invalid_client on
                  # a path nobody was looking at.
                  QITS_IDP_CLIENT_${ENV_KEY}_QITS_WORKSPACES_SECRET: "${IDP_SECRET_WORKSPACES}"
                  QITS_IDP_CLIENT_${ENV_KEY}_QITS_GATEWAY_SECRET: "${IDP_SECRET_GATEWAY}"
                  # The audiences each minting client may ask for. Restated in full, because the key replaces
                  # the shipped list rather than extending it — and an audience a client may not ask for is
                  # invalid_target, not a silent bare call. qits-ci is the one client that writes to the
                  # deployer (the build-succeeded intake), and this bootstrap borrows both identities for the
                  # events and the environment calls it makes by hand, so both lists are spelled. The
                  # deployer itself needs no client and no list: it mints nothing, it only validates.
                  QITS_IDP_CLIENT_${ENV_KEY}_QITS_CI_AUDIENCES: "${IDP_AUDIENCES}"
                  QITS_IDP_CLIENT_QITS_PLATFORM_ARTIFACTS_AUDIENCES: "${IDP_AUDIENCES}"
                  # The one claim grant phase 1 needs. The git host announces every push to ci's intake, which
                  # checks the token's project claim against the repo the event names — and the git host speaks
                  # for ALL repos, so its grant is the wildcard. The idp only states the claim; qits-ci's own
                  # enforcement is what reads '*' as covering every value.
                  QITS_IDP_CLIENT_QITS_PLATFORM_ARTIFACTS_CLAIMS_PROJECT: "*"
                  # WHERE TELEMETRY GOES, and it has to be spelled in every service below. The
                  # images ship the bare qits-observability, and that name died with the
                  # 2026-08-08 rename: observability is an environment service, so its alias
                  # carries the tier. An OTLP exporter dialling a name that does not resolve drops
                  # every trace and every log AND retries, so the whole platform goes dark while
                  # each container fills its own log with the attempts — which is how it was found
                  # on the first prod bootstrap.
                  QITS_OBSERVABILITY_URL: http://${ENV_NAME}-qits-observability:8080
                # No volume: /data held the H2 and nothing else, and the image has no mount point for it
                # any more.
                networks: [qits-net]
                restart: unless-stopped

              # THE HOST'S ONE PUBLISHED PORT. Every address this bootstrap dials on 127.0.0.1:${PORT}
              # arrives here first and is handed to the gateway of the environment the request's Host name
              # names — which for a workstation is always the default, because localhost carries no
              # environment label. It serves no paths of its own beyond /q, holds no state and has no client,
              # so the seed needs no volume and no placeholder bundle.
              #
              # In the seed because it is the door: qits-ci and qits-deployments publish no host port, and
              # the CLI reaches both through this process. Without it the first health poll has nothing to
              # ask.
              qits-platform-edge:
                image: qits/platform-edge:latest
                container_name: qits-platform-edge
                ports:
                  - "${PORT}:8080"${EDGE_TLS_PORTS}
                environment:
                  # The whole routing surface: which environments exist, and which one an unlabelled host
                  # (localhost, an IP) resolves to. The default MUST be a member of the list — the process
                  # refuses to start otherwise, rather than letting each request find out.
                  QITS_EDGE_ENVIRONMENTS: ${ENV_NAME}
                  QITS_EDGE_DEFAULT_ENVIRONMENT: ${ENV_NAME}
                  # How an environment name becomes an address. {env} is the only placeholder and this is
                  # the platform's own naming convention, so it equals the shipped default — spelled for the
                  # reason every address here is spelled, and because it is the ONE line that ties the edge
                  # to the wire aliases the rest of this file hands out.
                  QITS_EDGE_UPSTREAM_HOST_PATTERN: "{env}-qits-gateway"
                  QITS_EDGE_UPSTREAM_PORT: "8080"
                  QITS_OBSERVABILITY_URL: http://${ENV_NAME}-qits-observability:8080${EDGE_TLS}
                networks: [qits-net]
                restart: unless-stopped

              # THE HOST'S SECOND DOOR, and the only one that is not HTTP: the authoritative
              # nameserver for the platform's own names. A registrar delegates a domain to it and the
              # internet reaches it on 53; the record API on 8080 is service-to-service and has no
              # gateway route, deliberately — the gateway proxies HTTP and DNS is not HTTP, so this
              # is a SIBLING of the edge behind the same public IP rather than something behind it.
              #
              # A PLATFORM SERVICE: one delegated nameserver answers for every environment, because a
              # zone is a row. Two of them would be two servers claiming one IP's port 53 and
              # disagreeing about what exists.
              #
              # In the seed because this bootstrap writes to it: with QITS_DOMAIN set the zone row is
              # created over the API in this same run, hours before the pipeline could deploy it.
              # With no domain it runs with no zones at all, which its own README calls a legal state
              # — a server answering REFUSED for everything is what a platform with no public names
              # should have.
              qits-platform-dns:
                image: qits/platform-dns:latest
                container_name: qits-platform-dns
                ports:
                  # BOTH PROTOCOLS. dnsjava drops a whole RRset that will not fit a UDP answer, so a
                  # name with several records answers TC=1 and ZERO records and the client's TCP
                  # retry is the only way it ever gets one. Resolvers also probe TCP outright. The
                  # listener binds 8053 because below 1024 needs privileges this process should not
                  # hold, so the publish is what makes it 53.
                  - "${DNS_PORT}:8053/udp"
                  - "${DNS_PORT}:8053/tcp"
                environment:
                  # SPELLED HERE, AND ONLY HERE, exactly as the idp's and ci's are: compose starts
                  # this container before any deployer exists, so the bootstrap created the role and
                  # the database over JDBC and hands the credential over itself. Every deployment
                  # after this one is handed the same three by qits-platform-deployments, from
                  # `resources: postgresql:db` in this repository's deployments.yml — which is why
                  # the run-args line beside this file carries no datasource env either.
                  #
                  # It REFUSES TO BOOT without them, and for this service that is the failure worth
                  # having: a nameserver that came up on an empty store would answer NXDOMAIN for
                  # every deployed hostname, with nothing anywhere reporting an outage.
                  QITS_RESOURCE_DB_URL: jdbc:postgresql://${ENV_NAME}-qits-oci-postgresql:5432/qits_platform_dns
                  QITS_RESOURCE_DB_USERNAME: qits_platform_dns
                  QITS_RESOURCE_DB_PASSWORD: "${PG_PLATFORM_DNS_PASSWORD}"
                  QITS_OBSERVABILITY_URL: http://${ENV_NAME}-qits-observability:8080${DNS_IDENTITY}
                # No volume: the store is the postgres below and this service writes nothing that
                # outlives the container.
                networks: [qits-net]
                restart: unless-stopped

              # The platform's PostgreSQL. An ENVIRONMENT service — every tier runs its own — and the
              # deployer's own store, which is why it is in the seed at all: qits-deployments refuses to
              # boot without it, and nothing can deploy a database until the deployer answers.
              #
              # NO depends_on, here or on any consumer, and that is the compose-resurrection rule rather
              # than an omission: on later runs compose starts only the services the deployer does not
              # already manage, and a dependency would resurrect a compose sibling beside its deployed
              # replacement. The cold path is covered by ordering instead — the seed-postgres phase has
              # this server answering before this file is even written — and the warm path by the pair
              # below it: the deployer refuses to boot without its database and `restart: unless-stopped`
              # is the retry loop.
              #
              # No QITS_OBSERVABILITY_URL, deliberately: this is upstream postgres, not an OTLP client,
              # and the variable would be one more thing in `docker inspect` that means nothing.
              ${ENV_NAME}-qits-oci-postgresql:
                image: qits/oci-postgresql:latest
                container_name: ${ENV_NAME}-qits-oci-postgresql
                ports:
                  # For THIS CLI, bound to loopback like the registry port: the bootstrap creates roles
                  # and databases over ordinary JDBC from the host, and it keeps the port after the
                  # deployer replaces this container with its own.
                  - "127.0.0.1:${PG_PORT}:5432"
                environment:
                  # Generated by this bootstrap and recorded in .qits-bootstrap.env BEFORE the server
                  # first started. It applies at initdb only — on a volume that already holds a cluster
                  # this value is ignored, so the recorded one is the only way back in.
                  POSTGRES_PASSWORD: "${PG_SUPERUSER_PASSWORD}"
                volumes:
                  # /var/lib/postgresql, NOT /var/lib/postgresql/data — see the volume's own comment.
                  - qits-oci-postgresql-data:/var/lib/postgresql
                healthcheck:
                  # The database's own answer to "are you serving", and the same command the deployer
                  # gates its cutover with (health_cmd in this repository's deployments.yml). There is no
                  # HTTP endpoint to curl.
                  test: ["CMD-SHELL", "pg_isready -U postgres"]
                  interval: 10s
                  timeout: 5s
                  retries: 30
                networks: [qits-net]
                restart: unless-stopped

              # The deployer, and the topology it decides from: one component, one database, one docker
              # socket. It is the merge-back of qits-cd and qits-serviceregistry, so it stands where both
              # used to. In the seed because the '${ENV_NAME}' environment is created through it minutes
              # from now and because nothing else can start a container. No published host port of its own —
              # the edge and the gateway's /platform-deployments route are the door. Ready at
              # /platform-deployments/q/health/ready.
              #
              # An ENVIRONMENT service: one deployer per tier, deploying its own tier. Its route segment is
              # still /platform-deployments — that names the component, and only the repository was renamed.
              ${ENV_NAME}-qits-deployments:
                image: qits/deployments:latest
                container_name: ${ENV_NAME}-qits-deployments
                group_add: ["${DOCKER_GID}"]
                environment:
                  # ADOPTER #1 of the generic resource contract. Every application that declares
                  # `resources: postgresql:<name>` is handed QITS_RESOURCE_<NAME>_URL/_USERNAME/_PASSWORD
                  # by this very deployer; its own store arrives the same way, from the bootstrap rather
                  # than from itself. Unset, the binary refuses to boot at Flyway — which is what makes it
                  # safe to have no depends_on: a deployer that starts before its database simply restarts
                  # until the database is there.
                  #
                  # The role, the database and the username are one identity: qits_deployments.
                  QITS_RESOURCE_DB_URL: jdbc:postgresql://${ENV_NAME}-qits-oci-postgresql:5432/qits_deployments
                  QITS_RESOURCE_DB_USERNAME: qits_deployments
                  QITS_RESOURCE_DB_PASSWORD: "${PG_DEPLOYMENTS_PASSWORD}"
                  # Which tier this deployer is, so it can register its own resource row and resolve the
                  # postgres host of an environment application without asking itself first.
                  QITS_ENVIRONMENT: ${ENV_NAME}
                  # THE ADMIN CREDENTIAL, and what makes this component a provisioner rather than only a
                  # consumer: it is what lets it create the role and the database of every application
                  # that declares one. It lives in the same trust domain as the docker socket beside it.
                  QITS_PLATFORM_DEPLOYMENTS_POSTGRES_ADMIN_PASSWORD: "${PG_SUPERUSER_PASSWORD}"
                  # It pulls through the HOST daemon — same reasoning as ci's registry host.
                  QITS_ARTIFACTS_REGISTRY_HOST: localhost:${REGISTRY_PORT}
                  # Per-application run-args live in the qits-deployments-config volume
                  # (config/application.properties, written by the bootstrap), NOT here: a self-update's
                  # successor must inherit them, and env cannot nest those values.
                  # Machine auth, INBOUND ONLY. The build-succeeded intake and the topology writes demand a
                  # bearer addressed to this service; every read stays open. There is no oidc-client and no
                  # secret — the merge removed the peer its ancestor authenticated to.
                  #
                  # THE AUDIENCE IS ITS WIRE ALIAS AND HAS TO BE SPELLED. The shipped default is the old
                  # repository name, so a token minted for ${ENV_NAME}-qits-deployments would be refused by
                  # a service still expecting qits-platform-deployments — 401 on every build-succeeded, on a
                  # gate that looks correctly configured from both sides.
                  QITS_AUTH_MACHINE_AUDIENCE: ${ENV_NAME}-qits-deployments
                  QITS_AUTH_MACHINE_REQUIRED: "${MACHINE_REQUIRED}"
                  QUARKUS_OIDC_AUTH_SERVER_URL: ${IDP}
                  QITS_OBSERVABILITY_URL: http://${ENV_NAME}-qits-observability:8080
                volumes:
                  # No data volume any more: the store is the postgres above, and /data held the H2 files
                  # and nothing else. The config volume stays — it is the run-args a self-update's
                  # successor inherits.
                  - qits-deployments-config:/work/config
                  - /var/run/docker.sock:/var/run/docker.sock
                networks: [qits-net]
                restart: unless-stopped

              # No ports. The gateway is behind the edge now, and an environment service of ${ENV_NAME}
              # rather than a platform one: it was only ever on the platform plane because it bound the
              # host's port, and it does not.
              ${ENV_NAME}-qits-gateway:
                image: qits/gateway:latest
                container_name: ${ENV_NAME}-qits-gateway
                environment:
                  # The route table: an entry is both the on-switch and the target. Every value is a WIRE
                  # ALIAS — this tier's own services carry the tier's name, the platform's four do not.
                  # Aliases of the pipeline-deployed services resolve the moment the deployer cuts them
                  # over; until then those routes 502.
                  QITS_GATEWAY_PROXY_HOSTS_ARTIFACTS: qits-platform-artifacts   # also claims root-level /v2 (OCI registry)
                  QITS_GATEWAY_PROXY_HOSTS_CI: ${ENV_NAME}-qits-ci
                  QITS_GATEWAY_PROXY_HOSTS_PLATFORM_DEPLOYMENTS: ${ENV_NAME}-qits-deployments
                  QITS_GATEWAY_PROXY_HOSTS_OBSERVABILITY: ${ENV_NAME}-qits-observability
                  QITS_GATEWAY_PROXY_HOSTS_PROJECTS: ${ENV_NAME}-qits-projects
                  QITS_GATEWAY_PROXY_HOSTS_WORKSPACES: ${ENV_NAME}-qits-workspaces
                  QITS_GATEWAY_PROXY_HOSTS_STT: ${ENV_NAME}-qits-stt
                  QITS_GATEWAY_PROXY_HOSTS_EVENTS: ${ENV_NAME}-qits-events
                  QITS_GATEWAY_PROXY_HOSTS_PLATFORM_DOCS: qits-platform-docs
                  QITS_OBSERVABILITY_URL: http://${ENV_NAME}-qits-observability:8080
                networks: [qits-net]
                # No depends_on: on later runs compose starts only the services the deployer does not already
                # manage, and a dependency would resurrect a compose sibling next to its deployed replacement.
                restart: unless-stopped

              qits-platform-artifacts:
                image: qits/platform-artifacts:latest
                container_name: qits-platform-artifacts
                ports:
                  # For the HOST daemon only: ci publish steps push and the deployer pulls through the host's
                  # docker daemon, which cannot resolve qits-net aliases. localhost:${REGISTRY_PORT} is in
                  # docker's default insecure list, so plain HTTP needs no daemon config. It is also this
                  # CLI's own door: the bootstrap runs on the host now, not as a container on qits-net.
                  #
                  # The SECOND published port on the host, and the only one that is not the edge's. It is
                  # published for docker, not for people: the same service is reachable through the edge at
                  # /artifacts like every other route.
                  - "127.0.0.1:${REGISTRY_PORT}:8080"
                environment:
                  QUARKUS_DATASOURCE_ARTIFACTS_JDBC_URL: jdbc:h2:file:/data/artifacts/h2/artifacts
                  QITS_ARTIFACTS_BLOBS_DIR: /data/artifacts/blobs
                  # Where the git host's post-receive hook delivers. Fire-and-forget: wrong host = CI
                  # silently never runs.
                  QITS_CI_INTAKE_URL: http://${ENV_NAME}-qits-ci:8080/ci/api/events/post-receive
                  # The default branch's escape hatch: a push carrying -o qits.token=<this> is let through
                  # even when protection is on. Unset would mean no value matches and nothing overrides —
                  # which is the shipped default everywhere else, and which this bootstrap cannot live with
                  # (it pushes main many times before a release endpoint exists to go through).
                  QITS_REPOSITORIES_GIT_PUSH_TOKEN: "${PUSH_TOKEN}"
                  # Protection stays ON here too: the bootstrap's own pushes carry the token above, and a
                  # rerun that silently disarmed the seatbelt would be the quiet failure.
                  QITS_REPOSITORIES_GIT_PROTECT_DEFAULT_BRANCH: "true"
                  # Machine auth. Inbound: the admin writes under /artifacts/api demand a bearer addressed to
                  # qits-platform-artifacts. Outbound: the git host's post-receive announcement to qits-ci
                  # carries one. This service's audience needs no override — it is a platform service, so its
                  # wire alias IS its repository name, which is what the image already ships.
                  QITS_AUTH_MACHINE_REQUIRED: "${MACHINE_REQUIRED}"
                  QUARKUS_OIDC_AUTH_SERVER_URL: ${IDP}
                  # The outbound switch, and the secret it must never travel without. The service names the
                  # secret QITS_ARTIFACTS_CLIENT_SECRET in its own application.properties — the canonical
                  # QUARKUS_OIDC_CLIENT_CREDENTIALS_SECRET would override it too, but one spelling is enough
                  # and the file's own is the one that documents itself.
                  QUARKUS_OIDC_CLIENT_CLIENT_ENABLED: "${MACHINE_CLIENT}"
                  QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL: ${IDP}
                  # WHO THE OUTBOUND TOKEN IS FOR. The git host announces every push to ci's intake, and
                  # ci's identity is this tier's alias — the image asks for the unqualified qits-ci, which
                  # the idp answers invalid_target because no client may request an audience that does not
                  # exist. The client id needs no line: this is a platform service, so the shipped
                  # qits-platform-artifacts is already the alias.
                  QUARKUS_OIDC_CLIENT_GRANT_OPTIONS_CLIENT_AUDIENCE: ${ENV_NAME}-qits-ci
                  QITS_ARTIFACTS_CLIENT_SECRET: "${IDP_SECRET_PLATFORM_ARTIFACTS}"
                  QITS_OBSERVABILITY_URL: http://${ENV_NAME}-qits-observability:8080
                volumes:
                  - qits-platform-artifacts-data:/data
                networks: [qits-net]
                restart: unless-stopped

              ${ENV_NAME}-qits-ci:
                image: qits/ci:latest
                container_name: ${ENV_NAME}-qits-ci
                # Unprivileged uid stays; the socket group is all it needs.
                group_add: ["${DOCKER_GID}"]
                environment:
                  # TWO STORES, TWO TRIPLES. ci's own database and the outbox of the eventstream library
                  # it joins are two Flyway lineages and cannot share one. The library reads the
                  # `eventstream` name in its own shipped defaults, so the second triple's spelling is
                  # not a choice made here. Its file-H2 predecessor sat under ${user.home}, which a
                  # container has not got — that is gone with the H2.
                  #
                  # SPELLED HERE, AND ONLY HERE, for the same reason as the idp's above: compose starts
                  # this container before any deployer exists. Later deployments are handed the same six
                  # variables by qits-platform-deployments, from
                  # `resources: postgresql:db, postgresql:eventstream:qits_ci_eventstream` in this
                  # repository's deployments.yml.
                  QITS_RESOURCE_DB_URL: jdbc:postgresql://${ENV_NAME}-qits-oci-postgresql:5432/qits_ci
                  QITS_RESOURCE_DB_USERNAME: qits_ci
                  QITS_RESOURCE_DB_PASSWORD: "${PG_CI_PASSWORD}"
                  QITS_RESOURCE_EVENTSTREAM_URL: jdbc:postgresql://${ENV_NAME}-qits-oci-postgresql:5432/qits_ci_eventstream
                  QITS_RESOURCE_EVENTSTREAM_USERNAME: qits_ci_eventstream
                  QITS_RESOURCE_EVENTSTREAM_PASSWORD: "${PG_CI_EVENTSTREAM_PASSWORD}"
                  # ci's own fetch of the pushed ref, and the same base as seen from inside a step
                  # container — steps join qits-net, so both resolve the git host directly.
                  QITS_CI_GIT_HOST_URL: http://qits-platform-artifacts:8080/artifacts
                  QITS_CI_CONTAINER_GIT_URL: http://qits-platform-artifacts:8080/artifacts
                  # The network step containers join. Still qits-net: it is the deployer's legacy network,
                  # the one every container on this host is on whatever plane it belongs to.
                  QITS_CI_NETWORK: qits-net
                  # Where a green build is announced. Fire-and-forget and swallowed at debug, so a wrong
                  # value here deploys nothing and says nothing — which is exactly why it is spelled rather
                  # than inherited. The key is qits.platform.deployments.intake-url; the
                  # qits.cd.intake-url it replaced is gone rather than aliased.
                  QITS_PLATFORM_DEPLOYMENTS_INTAKE_URL: http://${ENV_NAME}-qits-deployments:8080/platform-deployments/api/events/build-succeeded
                  # Injected into publish steps as QITS_REGISTRY: dialled by the HOST daemon (see the
                  # qits-platform-artifacts ports note).
                  QITS_ARTIFACTS_REGISTRY_HOST: localhost:${REGISTRY_PORT}
                  # The npm roots (QITS_NPM_REGISTRY_URL / QITS_NPM_PROXY_URL) are deliberately NOT overridden
                  # here: a step container dials THOSE itself, on qits-net, so ci's shipped defaults are
                  # already right. Copying the localhost mapping above onto them would point every npm install
                  # at the step container's own loopback.
                  # The websocket a step container's daemon dials BACK to this service. The image ships the
                  # unqualified ws://qits-ci:8080/ci/daemon, and nothing by that alias exists any more — a
                  # blank here fails every step with "could not reach qits-ci", which is exactly how it was
                  # found on the first prod bootstrap.
                  QITS_CI_CONTAINER_DAEMON_URL: ws://${ENV_NAME}-qits-ci:8080/ci/daemon
                  # Same class of self-name: the release train asks workspaces for version identity.
                  QITS_CI_WORKSPACES_URL: http://${ENV_NAME}-qits-workspaces:8080
                  # The event bus. The eventstream jar's shipped default is the pre-rename
                  # `qits-events:8080`, which resolves to nothing on this network — measured: every
                  # outbox delivery of the seed ci dialled it, got ConnectException, and gave up
                  # after its five attempts. The deployed ci gets this same value from its run-args;
                  # the seed has to be told here, like every other wire name in this block.
                  QITS_EVENTS_URL: http://${ENV_NAME}-qits-events:8080
                  # The binary every step container downloads and execs — uploaded by this bootstrap, digest
                  # pinned. Blank would mean every run fails as never-registered.
                  QITS_CI_DAEMON_VERSION: "${DAEMON_SHA}"
                  # Machine auth. Inbound: /ci/api/events/* demands a bearer addressed to this service whose
                  # project claim covers the event's repo. Outbound: the build-succeeded notify to the
                  # deployer carries one.
                  #
                  # THE AUDIENCE IS ITS WIRE ALIAS AND HAS TO BE SPELLED, for the same reason the deployer's
                  # is: the image ships the unqualified qits-ci, and the idp mints ${ENV_NAME}-qits-ci.
                  QITS_AUTH_MACHINE_AUDIENCE: ${ENV_NAME}-qits-ci
                  QITS_AUTH_MACHINE_REQUIRED: "${MACHINE_REQUIRED}"
                  QUARKUS_OIDC_AUTH_SERVER_URL: ${IDP}
                  QUARKUS_OIDC_CLIENT_CLIENT_ENABLED: "${MACHINE_CLIENT}"
                  QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL: ${IDP}
                  # The client id and the audience it asks for are BOTH this tier's aliases, and the image
                  # ships the unqualified pair (qits-ci asking for qits-platform-deployments). Either one
                  # left alone is a token request the idp refuses — invalid_client for the first,
                  # invalid_target for the second — on a notify that is swallowed at debug.
                  QUARKUS_OIDC_CLIENT_CLIENT_ID: ${ENV_NAME}-qits-ci
                  QUARKUS_OIDC_CLIENT_GRANT_OPTIONS_CLIENT_AUDIENCE: ${ENV_NAME}-qits-deployments
                  QUARKUS_OIDC_CLIENT_CREDENTIALS_SECRET: "${IDP_SECRET_CI}"
                  QITS_OBSERVABILITY_URL: http://${ENV_NAME}-qits-observability:8080
                volumes:
                  # The socket and nothing else. ci's /data held the H2 files, and before that a bare git
                  # mirror per repository — it reads pipeline config off the git host's content routes
                  # now, so the image has no /data at all and this container writes nothing that outlives
                  # it. The socket stays: starting a step container is what this service does.
                  - /var/run/docker.sock:/var/run/docker.sock
                networks: [qits-net]
                restart: unless-stopped
            """;

    private static final String RUN_ARGS = """
            # Generated by qits-cli-bootstrap — qits.platform.deployments.run-args.<application>: what each deployed container
            # needs beyond its image. Whitespace-split, appended verbatim between the deployer's flags and the
            # image. The namespace was qits.cd.run-args before the merge-back; a deployment carrying the old
            # spelling configures nothing.
            #
            # An <application> is a REPOSITORY NAME, and six of them were renamed on 2026-08-08: a line under
            # a retired name configures nothing and the deployment comes up with no volumes and no env, which
            # is a container that boots, passes health and has lost its database.
            #
            # Every hostname in every value below is a WIRE ALIAS: ${ENV_NAME}-qits-<app> for a service of
            # this environment, the bare repository name for one of the four platform services.
            #
            # NO LINE BELOW CARRIES A DATASOURCE, with two exceptions that say why on themselves:
            # qits-platform-artifacts, the one service still on a file H2, and qits-deployments, whose
            # own store is the one credential the bootstrap issues and the deployer then registers as
            # its own. Every other store is DECLARED rather than configured: a
            # repository writes `resources: postgresql:<name>` in its .config/qits/deployments.yml, and
            # qits-platform-deployments creates the role and the database on this tier's postgres and
            # injects QITS_RESOURCE_<NAME>_URL / _USERNAME / _PASSWORD before the container starts. Those
            # variables are injected BEFORE the arguments here, and docker keeps the last -e — so a
            # datasource line here is an operator PIN that outlives a password rotation and breaks the
            # deployment it looks like it is configuring. The seed compose file spells the triples for
            # qits-ci and qits-platform-idp for the one reason that does not apply here: it starts them
            # before any deployer exists.
            #
            # EVERY LINE OF A QITS APPLICATION CARRIES QITS_OBSERVABILITY_URL, for the same reason the seed
            # compose spells it on every service: the images ship the bare qits-observability, and that
            # name died with the 2026-08-08 rename. An OTLP exporter dialling a name that does not resolve
            # drops every trace and every log AND retries, so the platform goes dark while each container
            # fills its own log with the attempts. qits-oci-postgresql is the one exception and says so on
            # its own line: it is upstream postgres, which has no exporter to point anywhere.
            #
            # THE HOST PORT IS THE EDGE'S. qits-gateway carries no -p at all any more; publishing it from two
            # applications is a bind conflict that only shows up on the second cutover.
            ${EDGE_TLS_NOTE}qits.platform.deployments.run-args.qits-platform-edge=-p ${PORT}:8080${EDGE_TLS_ARGS} -e QITS_EDGE_ENVIRONMENTS=${ENV_NAME} -e QITS_EDGE_DEFAULT_ENVIRONMENT=${ENV_NAME} -e QITS_EDGE_UPSTREAM_HOST_PATTERN={env}-qits-gateway -e QITS_EDGE_UPSTREAM_PORT=8080 -e QITS_OBSERVABILITY_URL=http://${ENV_NAME}-qits-observability:8080
            qits.platform.deployments.run-args.qits-gateway=-e QITS_GATEWAY_PROXY_HOSTS_ARTIFACTS=qits-platform-artifacts -e QITS_GATEWAY_PROXY_HOSTS_CI=${ENV_NAME}-qits-ci -e QITS_GATEWAY_PROXY_HOSTS_PLATFORM_DEPLOYMENTS=${ENV_NAME}-qits-deployments -e QITS_GATEWAY_PROXY_HOSTS_OBSERVABILITY=${ENV_NAME}-qits-observability -e QITS_GATEWAY_PROXY_HOSTS_PROJECTS=${ENV_NAME}-qits-projects -e QITS_GATEWAY_PROXY_HOSTS_WORKSPACES=${ENV_NAME}-qits-workspaces -e QITS_GATEWAY_PROXY_HOSTS_STT=${ENV_NAME}-qits-stt -e QITS_GATEWAY_PROXY_HOSTS_EVENTS=${ENV_NAME}-qits-events -e QITS_GATEWAY_PROXY_HOSTS_PLATFORM_DOCS=qits-platform-docs -e QITS_OBSERVABILITY_URL=http://${ENV_NAME}-qits-observability:8080
            # The push token rides here so it is already in place when the default branch's protection is
            # switched on: turning protection on is then one property on the artifacts side, not a two-part
            # change that could leave a running platform locked out of its own bootstrap.
            # No QITS_AUTH_MACHINE_AUDIENCE: this is a platform service, so its wire alias is its repository
            # name and the image's own default is already that.
            # The two GC pin sources. The image ships pre-rename names, and a pin source that cannot be
            # reached makes the sweep abort fail-closed rather than delete a live artifact — so every sweep
            # stops and the cleanup banner hangs on its timeout instead.
            # The two qits-projects dials. Both images default to a monolith-era localhost, which in a
            # standalone deployment means the service calls ITSELF and the call is swallowed:
            #   QITS_PROJECTS_INTAKE_URL     every push is announced here, and that announcement is what
            #                                triggers the repository's backup. Wrong value = no backups,
            #                                reported nowhere.
            #   QITS_PROJECTS_NAME_RESOLVER_URL  turns (projectId, repoName) into a repo id, which is what
            #                                makes the name-addressed git scheme
            #                                /artifacts/git/<projectId>/<repoName> serve instead of 404.
            #                                The project agent clones itself through that scheme, so unset
            #                                means an agent container with an empty /workspace. The PATH is
            #                                qits-projects'; only the host is a deployment decision.
            qits.platform.deployments.run-args.qits-platform-artifacts=-p 127.0.0.1:${REGISTRY_PORT}:8080 -v qits-platform-artifacts-data:/data -e QUARKUS_DATASOURCE_ARTIFACTS_JDBC_URL=jdbc:h2:file:/data/artifacts/h2/artifacts -e QITS_ARTIFACTS_BLOBS_DIR=/data/artifacts/blobs -e QITS_CI_INTAKE_URL=http://${ENV_NAME}-qits-ci:8080/ci/api/events/post-receive -e QITS_PROJECTS_INTAKE_URL=http://${ENV_NAME}-qits-projects:8080/projects/api/events/post-receive -e QITS_PROJECTS_NAME_RESOLVER_URL=http://${ENV_NAME}-qits-projects:8080/projects/api/projects -e QITS_REPOSITORIES_GIT_PUSH_TOKEN=${PUSH_TOKEN} -e QITS_REPOSITORIES_GIT_PROTECT_DEFAULT_BRANCH=true -e QITS_AUTH_MACHINE_REQUIRED=${MACHINE_REQUIRED} -e QUARKUS_OIDC_AUTH_SERVER_URL=${IDP} -e QUARKUS_OIDC_CLIENT_CLIENT_ENABLED=${MACHINE_CLIENT} -e QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL=${IDP} -e QUARKUS_OIDC_CLIENT_GRANT_OPTIONS_CLIENT_AUDIENCE=${ENV_NAME}-qits-ci -e QITS_ARTIFACTS_CLIENT_SECRET=${IDP_SECRET_PLATFORM_ARTIFACTS} -e QITS_ARTIFACTS_GC_PINS_CD_BASE_URL=http://${ENV_NAME}-qits-deployments:8080/platform-deployments/api -e QITS_ARTIFACTS_GC_PINS_CI_BASE_URL=http://${ENV_NAME}-qits-ci:8080/ci/api -e QITS_OBSERVABILITY_URL=http://${ENV_NAME}-qits-observability:8080
            # QITS_PLATFORM_DEPLOYMENTS_INTAKE_URL is where a green build is announced. The notify is
            # fire-and-forget and swallowed at debug, so a wrong value deploys nothing and reports nothing.
            # QITS_AUTH_MACHINE_AUDIENCE and QUARKUS_OIDC_CLIENT_CLIENT_ID are both this tier's alias: ci
            # ships the unqualified qits-ci for each, and the idp knows neither name.
            #
            # NO DATASOURCE ENV, AND NO DATA VOLUME — and the asymmetry with the seed compose block is
            # deliberate. ci's deployments.yml declares
            # `resources: postgresql:db, postgresql:eventstream:qits_ci_eventstream`, so the deployer
            # creates both databases before the successor container starts and injects the six
            # QITS_RESOURCE_* variables itself, from the registry row that holds the current password.
            # A line here would be an operator PIN — run-args are appended after the injected env and
            # docker keeps the last -e — so it would survive the deployer rotating that password and
            # break the deployment it looks like it is configuring. The seed block spells the same
            # variables because at that moment no deployer exists to inject anything. The /data volume
            # went with the H2: the image has no mount point for it any more.
            qits.platform.deployments.run-args.qits-ci=-v /var/run/docker.sock:/var/run/docker.sock --group-add ${DOCKER_GID} -e QITS_CI_GIT_HOST_URL=http://qits-platform-artifacts:8080/artifacts -e QITS_CI_CONTAINER_GIT_URL=http://qits-platform-artifacts:8080/artifacts -e QITS_CI_NETWORK=qits-net -e QITS_PLATFORM_DEPLOYMENTS_INTAKE_URL=http://${ENV_NAME}-qits-deployments:8080/platform-deployments/api/events/build-succeeded -e QITS_ARTIFACTS_REGISTRY_HOST=localhost:${REGISTRY_PORT} -e QITS_CI_DAEMON_VERSION=${DAEMON_SHA} -e QITS_CI_CONTAINER_DAEMON_URL=ws://${ENV_NAME}-qits-ci:8080/ci/daemon -e QITS_CI_WORKSPACES_URL=http://${ENV_NAME}-qits-workspaces:8080 -e QITS_EVENTS_URL=http://${ENV_NAME}-qits-events:8080 -e QITS_AUTH_MACHINE_AUDIENCE=${ENV_NAME}-qits-ci -e QITS_AUTH_MACHINE_REQUIRED=${MACHINE_REQUIRED} -e QUARKUS_OIDC_AUTH_SERVER_URL=${IDP} -e QUARKUS_OIDC_CLIENT_CLIENT_ENABLED=${MACHINE_CLIENT} -e QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL=${IDP} -e QUARKUS_OIDC_CLIENT_CLIENT_ID=${ENV_NAME}-qits-ci -e QUARKUS_OIDC_CLIENT_GRANT_OPTIONS_CLIENT_AUDIENCE=${ENV_NAME}-qits-deployments -e QUARKUS_OIDC_CLIENT_CREDENTIALS_SECRET=${IDP_SECRET_CI} -e QITS_OBSERVABILITY_URL=http://${ENV_NAME}-qits-observability:8080
            # The platform's PostgreSQL, deployed like everything else. The host publish is kept so this
            # CLI can reconnect to the same server after the deployer replaces the seed container with its
            # own — the seed's port would otherwise go with the seed. The mount path is
            # /var/lib/postgresql and not /var/lib/postgresql/data: postgres 18 keeps PGDATA at
            # /var/lib/postgresql/18/docker, and the old path mounts the volume BESIDE the cluster, which
            # writes every byte into the container layer and loses it on the next recreate.
            #
            # POSTGRES_PASSWORD applies at initdb only, so on this cutover it is inert — the volume
            # already holds an initialised cluster. It is spelled anyway, because the run-args are also
            # what a cold deployment on a fresh volume would use. One superuser password for the whole
            # platform until there is per-tier configuration to hold more than one.
            qits.platform.deployments.run-args.qits-oci-postgresql=-p 127.0.0.1:${PG_PORT}:5432 -v qits-oci-postgresql-data:/var/lib/postgresql -e POSTGRES_PASSWORD=${PG_SUPERUSER_PASSWORD}
            # The deployer's own deployment — the self-update handoff. Two mounts and a socket, all
            # load-bearing: the config volume holds this very file so the successor inherits every line of
            # it, and the docker socket is what makes it a deployer at all. There is no data volume: the
            # topology, the deployment history and the resource credentials live in postgres now, and the
            # QITS_RESOURCE_DB_* triple is how this component consumes the same contract it hands every
            # other application. QITS_PLATFORM_DEPLOYMENTS_POSTGRES_ADMIN_PASSWORD is what lets it
            # provision one. Machine auth INBOUND only: it validates qits-ci's bearer and mints nothing, so
            # no oidc-client and no secret — but the audience it validates AGAINST is this tier's alias, and
            # the image still ships the pre-rename repository name.
            qits.platform.deployments.run-args.qits-deployments=-v qits-deployments-config:/work/config -v /var/run/docker.sock:/var/run/docker.sock --group-add ${DOCKER_GID} -e QITS_RESOURCE_DB_URL=jdbc:postgresql://${ENV_NAME}-qits-oci-postgresql:5432/qits_deployments -e QITS_RESOURCE_DB_USERNAME=qits_deployments -e QITS_RESOURCE_DB_PASSWORD=${PG_DEPLOYMENTS_PASSWORD} -e QITS_ENVIRONMENT=${ENV_NAME} -e QITS_PLATFORM_DEPLOYMENTS_POSTGRES_ADMIN_PASSWORD=${PG_SUPERUSER_PASSWORD} -e QITS_ARTIFACTS_REGISTRY_HOST=localhost:${REGISTRY_PORT} -e QITS_AUTH_MACHINE_AUDIENCE=${ENV_NAME}-qits-deployments -e QITS_AUTH_MACHINE_REQUIRED=${MACHINE_REQUIRED} -e QUARKUS_OIDC_AUTH_SERVER_URL=${IDP} -e QITS_OBSERVABILITY_URL=http://${ENV_NAME}-qits-observability:8080
            # The idp's own deployment. NO DATASOURCE ENV AND NO VOLUME: `resources: postgresql:db` in its
            # deployments.yml is what gets it a store, and the deployer injects the triple from the
            # registry row before the successor starts. That row is what keeps the SIGNING KEY across
            # deployments — a redeploy landing on a fresh database mints a new keypair and invalidates
            # every token in flight — and pinning the triple here would outlive a rotation and break it.
            # The seed compose block spells the same three variables because it starts the idp before any
            # deployer exists. /data held the H2 and nothing else, so the volume went with it.
            # The claims grant is the git host's wildcard — it announces pushes for every repo, so its
            # project claim covers every value.
            # QITS_IDP_CLIENTS and both audience lists are restated in full, because each key REPLACES the
            # shipped list rather than extending it — and every id in them is a wire alias, so they move with
            # the environment name while the image's defaults cannot.
            qits.platform.deployments.run-args.qits-platform-idp=-e QITS_IDP_ISSUER=${IDP} -e QITS_IDP_CLIENTS=${IDP_CLIENTS} -e QITS_IDP_CLIENT_${ENV_KEY}_QITS_CI_SECRET=${IDP_SECRET_CI} -e QITS_IDP_CLIENT_QITS_PLATFORM_ARTIFACTS_SECRET=${IDP_SECRET_PLATFORM_ARTIFACTS} -e QITS_IDP_CLIENT_${ENV_KEY}_QITS_WORKSPACES_SECRET=${IDP_SECRET_WORKSPACES} -e QITS_IDP_CLIENT_${ENV_KEY}_QITS_GATEWAY_SECRET=${IDP_SECRET_GATEWAY} -e QITS_IDP_CLIENT_${ENV_KEY}_QITS_CI_AUDIENCES=${IDP_AUDIENCES} -e QITS_IDP_CLIENT_QITS_PLATFORM_ARTIFACTS_AUDIENCES=${IDP_AUDIENCES} -e QITS_IDP_CLIENT_QITS_PLATFORM_ARTIFACTS_CLAIMS_PROJECT=* -e QITS_OBSERVABILITY_URL=http://${ENV_NAME}-qits-observability:8080
            # The nameserver's own deployment. TWO PUBLISHES, BOTH PROTOCOLS: the deployed container
            # is what answers a registrar's delegation, so a -p missing here is a domain that stops
            # resolving at the first cutover, and a missing /tcp loses every answer too big for a UDP
            # packet. The port is the same knob the seed publishes (QITS_DNS_PORT), because a
            # delegation cannot follow a port that moved.
            #
            # NO DATASOURCE ENV AND NO VOLUME: `resources: postgresql:db` in its deployments.yml is
            # what gets it a store, and the deployer injects the triple from its registry row before
            # the successor starts — pinning it here would outlive a rotation and break the
            # deployment it looks like it is configuring. The seed compose block spells the same three
            # variables because it starts this container before any deployer exists.
            #
            # No machine auth: the record API's write guard is qits.dns.token, which this platform
            # leaves blank, and there is no gateway route to reach it from outside qits-net.
            qits.platform.deployments.run-args.qits-platform-dns=-p ${DNS_PORT}:8053/udp -p ${DNS_PORT}:8053/tcp -e QITS_OBSERVABILITY_URL=http://${ENV_NAME}-qits-observability:8080${DNS_IDENTITY_ARGS}
            qits.platform.deployments.run-args.qits-stt=-v qits-stt-data:/data -e QITS_SPEECH_HOME=/data/speech -e QITS_OBSERVABILITY_URL=http://${ENV_NAME}-qits-observability:8080
            # THE VOLUME STAYS AND THE DATASOURCE ENV IS GONE, which is the whole shape of this service's
            # move to postgres. /data is not the database's — it is QITS_PROJECTS_DATA_DIR below, the git
            # mirrors this service clones and the credentials beside them, files that no database
            # replaced. Both stores are declared instead: `resources: postgresql:db, postgresql:epics:
            # qits_epics` in projects' deployments.yml, and the deployer injects QITS_RESOURCE_DB_* and
            # QITS_RESOURCE_EPICS_* from its registry. Pinning either triple here would outlive a
            # rotation and break the deployment it looks like it is configuring.
            #
            # projects no longer mounts the shared repositories volume at all — it clones its own git mirrors
            # over the wire, through qits.artifacts.url, into its own data dir. QITS_PROJECTS_DATA_DIR is
            # spelled here rather than left to the image default (${user.home}/...), which resolves to the
            # literal "?" under this image's passwd-less UID 1001.
            #
            # QITS_REPOSITORIES_GIT_PUSH_TOKEN is the SAME token qits-platform-artifacts' hook checks, one
            # line above. projects advances refs on the git host by pushing now, and the default branch is
            # protected here, so without the token every pull that fast-forwards main is refused. A branch
            # delete deliberately sends no token.
            #
            # NO QITS_PROJECTS_AGENT_IMAGE, and its absence is the fix. It used to name
            # qits/project-agent:native — a tag built by hand on one machine, which the unwrap deleted
            # and no pipeline rebuilt, so every refinement agent start failed on an image that did not
            # exist. qits-projects-daemon's release pipeline publishes qits/project-agent:<version>
            # now, and qits-projects ships the registry-qualified pin, which a release train moves. An
            # override here would freeze that pin at whatever this file last said. Same reason
            # qits-workspaces' run-args do not name QITS_WORKSPACE_IMAGE.
            #
            # The docker socket, on the same terms qits-ci and qits-workspaces have it: DockerAgentRuntime
            # shells `docker run` to create a project's agent container, so without the socket every agent
            # start fails at the runtime rather than at a config check. The mount hands this container
            # control of the host daemon, which is root-equivalent — the service's own docs call supplying
            # it a deliberate deployment act rather than an image default, and this line IS that act.
            #
            # QITS_PROJECTS_OWN_HOST and QITS_PROJECTS_AGENT_GIT_BASE are the two addresses an agent
            # container is handed at creation: this service's own wire name, and the git host it clones
            # from. The image ships pre-rename defaults (qits-projects, qits-artifacts), which resolve to
            # nothing on this platform, so a container created from them never dials back and its boot
            # clone fails. Both are spelled here, the first with the environment's own prefix.
            qits.platform.deployments.run-args.qits-projects=-v qits-projects-data:/data -v /var/run/docker.sock:/var/run/docker.sock --group-add ${DOCKER_GID} -e QITS_PROJECTS_DATA_DIR=/data/mirrors -e QITS_ARTIFACTS_URL=http://qits-platform-artifacts:8080 -e QITS_REPOSITORIES_GIT_PUSH_TOKEN=${PUSH_TOKEN} -e QITS_PROJECTS_OWN_HOST=${ENV_NAME}-qits-projects -e QITS_PROJECTS_AGENT_GIT_BASE=http://qits-platform-artifacts:8080/artifacts/git -e QITS_OBSERVABILITY_URL=http://${ENV_NAME}-qits-observability:8080
            # The volume stays for the same reason qits-projects' does: /data is this service's own tree of
            # per-repository files, not a database. Both its stores — its own and the eventstream outbox —
            # are declared in its deployments.yml and injected by the deployer, so no datasource env is
            # here either.
            # QITS_ARTIFACTS_URL is where release PUSHES the release commit — the git host, over HTTP, so
            # the ordinary post-receive fires and the ordinary pipeline builds it. QITS_EVENTS_URL is where
            # the outbox drains to.
            # QITS_WORKSPACE_GIT_HOST (qits.workspace.git-host) is the address a WORKSPACE container uses to
            # reach this platform — git clone/push, OTLP, the agent's MCP servers and the daemon control
            # socket are all composed as http://<this>:8080/... It must be spelled, because the sentinel
            # "auto" is wrong on this topology and wrong silently: auto detects WSL2 and answers the primary
            # LAN IPv4, which is the address of the machine when qits runs ON the host — but qits-workspaces
            # runs in a container here, so what it measures is its OWN container's address and every
            # container->platform URL 404s. The gateway, not qits-workspaces or the artifacts service: it is
            # the one name on qits-net that fronts a WHOLE environment. Not the edge either — a workspace
            # belongs to a tier, and the gateway is the tier's own front door, while the edge exists to pick
            # between tiers for traffic that arrived from outside.
            qits.platform.deployments.run-args.qits-workspaces=-v qits-workspaces-data:/data -v /var/run/docker.sock:/var/run/docker.sock --group-add ${DOCKER_GID} -e QITS_PROJECTS_URL=http://${ENV_NAME}-qits-projects:8080 -e QITS_ARTIFACTS_URL=http://qits-platform-artifacts:8080 -e QITS_EVENTS_URL=http://${ENV_NAME}-qits-events:8080 -e QITS_WORKSPACE_GIT_HOST=${ENV_NAME}-qits-gateway -e QITS_WORKSPACES_RELEASE_ENTRY_BRANCH=environment/${ENV_NAME} -e QITS_OBSERVABILITY_URL=http://${ENV_NAME}-qits-observability:8080
            # The reading surface over qits-platform-artifacts' docs repository. ONE line and no volume,
            # because this service stores nothing — `latest` is a query over the store's rows rather
            # than a pointer it holds, so a redeploy loses nothing and there is no datasource URL to
            # spell. The address equals the service's own shipped default and is spelled anyway, for
            # the reason qits-projects' QITS_ARTIFACTS_URL is: an address a deployment inherits
            # silently is an address nobody knows to change. It is the SAME value qits-ci injects
            # into a publishing step as $QITS_DOCS_URL, so the publisher and the reader cannot
            # disagree about where documentation lives.
            qits.platform.deployments.run-args.qits-platform-docs=-e QITS_PLATFORM_DOCS_ARTIFACTS_URL=http://qits-platform-artifacts:8080/artifacts/docs/docs -e QITS_OBSERVABILITY_URL=http://${ENV_NAME}-qits-observability:8080
            # One line and no volume: this service's log is a database it declares
            # (`resources: postgresql:db`) and is handed by the deployer, and its image dropped the /data
            # mount point with the H2 — it writes nothing that outlives the container.
            qits.platform.deployments.run-args.qits-events=-e QITS_OBSERVABILITY_URL=http://${ENV_NAME}-qits-observability:8080
            # The receiver's own telemetry, addressed to itself. That is the consistent answer rather than
            # the clever one: qits-observability is an ordinary OTLP client like every application above,
            # and leaving it on the dead default would keep exactly one container spamming retries. This
            # application needed nothing beyond its image until the address had to be spelled, which is why
            # it had no line at all.
            qits.platform.deployments.run-args.qits-observability=-e QITS_OBSERVABILITY_URL=http://${ENV_NAME}-qits-observability:8080
            """;
}
