package eu.wohlben.qits.cli.bootstrap.platform;

import java.util.Map;

/**
 * The seed stack and qits-deployments' run-args, generated. Both are ports of the heredocs in
 * {@code qits-local-up.sh}, comments and all: the comments are where the reasons live, and a
 * generated file nobody can read is a file nobody can fix.
 * <p>
 * <b>Every service below is keyed and named by its WIRE ALIAS</b> — {@code prod-qits-ci} for an
 * environment service, {@code qits-platform-idp} for a platform one, exactly what
 * {@link PlatformModel#wireAlias} derives and exactly what the deployer will give the container
 * that replaces it. A container's own name resolves on a user-defined network the way an alias
 * does, so naming the seed after the alias is what makes the addresses in this very file — and in
 * the run-args beside it — right from the first second rather than from the first cutover. It is
 * also how the deployer finds its predecessor: it searches the qualified alias AND the bare
 * application name, so a seed under either spelling is adopted rather than left running beside its
 * replacement.
 */
public final class ComposeTemplate {

    private ComposeTemplate() {
    }

    public static String compose(Map<String, String> values) {
        return Tokens.apply(COMPOSE, values);
    }

    public static String runArgs(Map<String, String> values) {
        return Tokens.apply(RUN_ARGS, values);
    }

    private static final String COMPOSE = """
            # Generated by qits-cli-bootstrap — the SEED of the local qits platform: only the services that
            # build and deploy the rest. Everything else (observability, stt, projects, workspaces, events) is
            # deployed by qits-deployments through the main pipeline and is deliberately NOT in this file —
            # look for it in `docker ps` under qits-pd-${ENV_NAME}-qits-* container names (qits-pd-qits-* for
            # the four platform services), redeployed on every green push.
            #
            # Manage with: docker compose -p qits -f ${COMPOSE_FILE} ps|logs -f|down
            # (compose down leaves deployed containers running; remove those via the deployer's API or docker.)

            name: qits

            networks:
              qits-net:
                # The one shared network: seed services, deployed applications and ci step containers all
                # join it and resolve each other by alias. It is the deployer's
                # qits.platform.deployments.legacy-network, which every container it starts also joins while
                # the platform still holds direct cross-application URLs. External because the bootstrap (or a previous stack, or qits-ci's
                # own boot) may have created it already — compose refuses to adopt a network it did not
                # label.
                name: qits-net
                external: true

            volumes:
              # Every volume is keyed by the APPLICATION it belongs to, because the deployer's run-args
              # reference them by name and an application's run-args are looked up by that same name.
              #
              # qits-platform-artifacts' store: blobs, packages and the git host's repositories — which are
              # blobs too now, so the git host needs no volume of its own.
              qits-platform-artifacts-data:
                name: qits-platform-artifacts-data
              qits-ci-data:
                name: qits-ci-data
              # THE PLATFORM'S TOPOLOGY AND ITS DEPLOYMENT HISTORY LIVE HERE — every environment, every
              # service, every link, every deployment row and the rollback pins read off them. One database
              # for one component; the image refuses to boot without the url that points at this volume,
              # because a redeploy onto ephemeral storage would come up healthy and empty and then reconcile
              # every environment against an empty catalogue.
              qits-deployments-data:
                name: qits-deployments-data
              # THE SIGNING KEY LIVES HERE. An idp on ephemeral storage comes up healthy and mints a new
              # keypair on every recreate, invalidating every token in flight with nothing in any log to say
              # why — which is why its image refuses to boot without the url that points at this volume.
              qits-platform-idp-data:
                name: qits-platform-idp-data
              # Mounted by DEPLOYED containers via qits.platform.deployments.run-args, not by any service
              # below.
              qits-projects-data:
                name: qits-projects-data
              qits-workspaces-data:
                name: qits-workspaces-data
              qits-stt-data:
                name: qits-stt-data
              qits-events-data:
                name: qits-events-data
              # The deployer's run-args config (config/application.properties, written by the bootstrap). A
              # volume rather than env so a self-update's successor inherits it — env cannot nest these
              # values.
              qits-deployments-config:
                name: qits-deployments-config

            # Each key below is the service's WIRE ALIAS, and so is its container_name: a container's own
            # name resolves on this network exactly as an alias does, so the seed answers to the address
            # every run-arg in the generated properties file already carries. An environment service is
            # ${ENV_NAME}-qits-<app>; a platform service is its bare repository name, which says the plane
            # itself.
            services:
              # The issuer. No published host port and no gateway route: in phase 1 nothing outside qits-net
              # talks to it, and /idp/token reachable from the host through an unauthenticated gateway would be
              # a token vending machine. Phase 3's user flows are what put it on the route table.
              #
              # First in this file because it is first in the order that matters: every service below mints or
              # validates against it, and the git host's very first post-receive needs a token.
              qits-platform-idp:
                image: qits/platform-idp:latest
                container_name: qits-platform-idp
                environment:
                  # Not a default the image could ship: the signing key lands in this database, and the image
                  # refuses to boot rather than write it into a container layer.
                  QUARKUS_DATASOURCE_IDP_JDBC_URL: jdbc:h2:file:/data/idp/h2/idp
                  # The 'iss' of every token and the base of every endpoint the discovery document advertises.
                  # Spelled here although it equals the shipped default, for the reason every other address in
                  # this file is spelled: an address a deployment inherits silently is one nobody knows to
                  # change. Consumers below carry the same string; a mismatch is rejected at validation.
                  QITS_IDP_ISSUER: ${IDP}
                  # WHICH CLIENTS EXIST. The key REPLACES the shipped list rather than extending it, and an
                  # id that is not on it is unknown — invalid_client, with nothing to say it was a typo. It is
                  # spelled because a client id is a wire alias now, so it moves with the environment name.
                  QITS_IDP_CLIENTS: "${IDP_CLIENTS}"
                  # Generated by this bootstrap, recorded in .qits-bootstrap.env, and handed to the matching
                  # service below. A client without a secret is refused, never open.
                  QITS_IDP_CLIENT_${ENV_KEY}_QITS_CI_SECRET: "${IDP_SECRET_CI}"
                  QITS_IDP_CLIENT_QITS_PLATFORM_ARTIFACTS_SECRET: "${IDP_SECRET_PLATFORM_ARTIFACTS}"
                  # Unused in phase 1 (qits-workspaces' agents are phase 2, the gateway's user flows phase 3).
                  # Seeded anyway: the cost is a config line, and the cost of the omission is invalid_client on
                  # a path nobody was looking at.
                  QITS_IDP_CLIENT_${ENV_KEY}_QITS_WORKSPACES_SECRET: "${IDP_SECRET_WORKSPACES}"
                  QITS_IDP_CLIENT_${ENV_KEY}_QITS_GATEWAY_SECRET: "${IDP_SECRET_GATEWAY}"
                  # The audiences each minting client may ask for. Restated in full, because the key replaces
                  # the shipped list rather than extending it — and an audience a client may not ask for is
                  # invalid_target, not a silent bare call. qits-ci is the one client that writes to the
                  # deployer (the build-succeeded intake), and this bootstrap borrows both identities for the
                  # events and the environment calls it makes by hand, so both lists are spelled. The
                  # deployer itself needs no client and no list: it mints nothing, it only validates.
                  QITS_IDP_CLIENT_${ENV_KEY}_QITS_CI_AUDIENCES: "${IDP_AUDIENCES}"
                  QITS_IDP_CLIENT_QITS_PLATFORM_ARTIFACTS_AUDIENCES: "${IDP_AUDIENCES}"
                  # The one claim grant phase 1 needs. The git host announces every push to ci's intake, which
                  # checks the token's project claim against the repo the event names — and the git host speaks
                  # for ALL repos, so its grant is the wildcard. The idp only states the claim; qits-ci's own
                  # enforcement is what reads '*' as covering every value.
                  QITS_IDP_CLIENT_QITS_PLATFORM_ARTIFACTS_CLAIMS_PROJECT: "*"
                  # WHERE TELEMETRY GOES, and it has to be spelled in every service below. The
                  # images ship the bare qits-observability, and that name died with the
                  # 2026-08-08 rename: observability is an environment service, so its alias
                  # carries the tier. An OTLP exporter dialling a name that does not resolve drops
                  # every trace and every log AND retries, so the whole platform goes dark while
                  # each container fills its own log with the attempts — which is how it was found
                  # on the first prod bootstrap.
                  QITS_OBSERVABILITY_URL: http://${ENV_NAME}-qits-observability:8080
                volumes:
                  - qits-platform-idp-data:/data
                networks: [qits-net]
                restart: unless-stopped

              # THE HOST'S ONE PUBLISHED PORT. Every address this bootstrap dials on 127.0.0.1:${PORT}
              # arrives here first and is handed to the gateway of the environment the request's Host name
              # names — which for a workstation is always the default, because localhost carries no
              # environment label. It serves no paths of its own beyond /q, holds no state and has no client,
              # so the seed needs no volume and no placeholder bundle.
              #
              # In the seed because it is the door: qits-ci and qits-deployments publish no host port, and
              # the CLI reaches both through this process. Without it the first health poll has nothing to
              # ask.
              qits-platform-edge:
                image: qits/platform-edge:latest
                container_name: qits-platform-edge
                ports:
                  - "${PORT}:8080"
                environment:
                  # The whole routing surface: which environments exist, and which one an unlabelled host
                  # (localhost, an IP) resolves to. The default MUST be a member of the list — the process
                  # refuses to start otherwise, rather than letting each request find out.
                  QITS_EDGE_ENVIRONMENTS: ${ENV_NAME}
                  QITS_EDGE_DEFAULT_ENVIRONMENT: ${ENV_NAME}
                  # How an environment name becomes an address. {env} is the only placeholder and this is
                  # the platform's own naming convention, so it equals the shipped default — spelled for the
                  # reason every address here is spelled, and because it is the ONE line that ties the edge
                  # to the wire aliases the rest of this file hands out.
                  QITS_EDGE_UPSTREAM_HOST_PATTERN: "{env}-qits-gateway"
                  QITS_EDGE_UPSTREAM_PORT: "8080"
                  QITS_OBSERVABILITY_URL: http://${ENV_NAME}-qits-observability:8080
                networks: [qits-net]
                restart: unless-stopped

              # The deployer, and the topology it decides from: one component, one database, one docker
              # socket. It is the merge-back of qits-cd and qits-serviceregistry, so it stands where both
              # used to. In the seed because the '${ENV_NAME}' environment is created through it minutes
              # from now and because nothing else can start a container. No published host port of its own —
              # the edge and the gateway's /platform-deployments route are the door. Ready at
              # /platform-deployments/q/health/ready.
              #
              # An ENVIRONMENT service: one deployer per tier, deploying its own tier. Its route segment is
              # still /platform-deployments — that names the component, and only the repository was renamed.
              ${ENV_NAME}-qits-deployments:
                image: qits/deployments:latest
                container_name: ${ENV_NAME}-qits-deployments
                group_add: ["${DOCKER_GID}"]
                environment:
                  # Same reason as the idp's twin above: the shipped default sits under ${user.home}, which
                  # this image's passwd-less UID 1001 has not got, so the binary dies at Flyway rather than
                  # writing the platform's topology into a container layer.
                  QUARKUS_DATASOURCE_PLATFORMDEPLOYMENTS_JDBC_URL: jdbc:h2:file:/data/platformdeployments/h2/platformdeployments
                  # It pulls through the HOST daemon — same reasoning as ci's registry host.
                  QITS_ARTIFACTS_REGISTRY_HOST: localhost:${REGISTRY_PORT}
                  # Per-application run-args live in the qits-deployments-config volume
                  # (config/application.properties, written by the bootstrap), NOT here: a self-update's
                  # successor must inherit them, and env cannot nest those values.
                  # Machine auth, INBOUND ONLY. The build-succeeded intake and the topology writes demand a
                  # bearer addressed to this service; every read stays open. There is no oidc-client and no
                  # secret — the merge removed the peer its ancestor authenticated to.
                  #
                  # THE AUDIENCE IS ITS WIRE ALIAS AND HAS TO BE SPELLED. The shipped default is the old
                  # repository name, so a token minted for ${ENV_NAME}-qits-deployments would be refused by
                  # a service still expecting qits-platform-deployments — 401 on every build-succeeded, on a
                  # gate that looks correctly configured from both sides.
                  QITS_AUTH_MACHINE_AUDIENCE: ${ENV_NAME}-qits-deployments
                  QITS_AUTH_MACHINE_REQUIRED: "${MACHINE_REQUIRED}"
                  QUARKUS_OIDC_AUTH_SERVER_URL: ${IDP}
                  QITS_OBSERVABILITY_URL: http://${ENV_NAME}-qits-observability:8080
                volumes:
                  - qits-deployments-data:/data
                  - qits-deployments-config:/work/config
                  - /var/run/docker.sock:/var/run/docker.sock
                networks: [qits-net]
                restart: unless-stopped

              # No ports. The gateway is behind the edge now, and an environment service of ${ENV_NAME}
              # rather than a platform one: it was only ever on the platform plane because it bound the
              # host's port, and it does not.
              ${ENV_NAME}-qits-gateway:
                image: qits/gateway:latest
                container_name: ${ENV_NAME}-qits-gateway
                environment:
                  # The route table: an entry is both the on-switch and the target. Every value is a WIRE
                  # ALIAS — this tier's own services carry the tier's name, the platform's four do not.
                  # Aliases of the pipeline-deployed services resolve the moment the deployer cuts them
                  # over; until then those routes 502.
                  QITS_GATEWAY_PROXY_HOSTS_ARTIFACTS: qits-platform-artifacts   # also claims root-level /v2 (OCI registry)
                  QITS_GATEWAY_PROXY_HOSTS_CI: ${ENV_NAME}-qits-ci
                  QITS_GATEWAY_PROXY_HOSTS_PLATFORM_DEPLOYMENTS: ${ENV_NAME}-qits-deployments
                  QITS_GATEWAY_PROXY_HOSTS_OBSERVABILITY: ${ENV_NAME}-qits-observability
                  QITS_GATEWAY_PROXY_HOSTS_PROJECTS: ${ENV_NAME}-qits-projects
                  QITS_GATEWAY_PROXY_HOSTS_WORKSPACES: ${ENV_NAME}-qits-workspaces
                  QITS_GATEWAY_PROXY_HOSTS_STT: ${ENV_NAME}-qits-stt
                  QITS_GATEWAY_PROXY_HOSTS_EVENTS: ${ENV_NAME}-qits-events
                  QITS_GATEWAY_PROXY_HOSTS_PLATFORM_DOCS: qits-platform-docs
                  QITS_OBSERVABILITY_URL: http://${ENV_NAME}-qits-observability:8080
                networks: [qits-net]
                # No depends_on: on later runs compose starts only the services the deployer does not already
                # manage, and a dependency would resurrect a compose sibling next to its deployed replacement.
                restart: unless-stopped

              qits-platform-artifacts:
                image: qits/platform-artifacts:latest
                container_name: qits-platform-artifacts
                ports:
                  # For the HOST daemon only: ci publish steps push and the deployer pulls through the host's
                  # docker daemon, which cannot resolve qits-net aliases. localhost:${REGISTRY_PORT} is in
                  # docker's default insecure list, so plain HTTP needs no daemon config. It is also this
                  # CLI's own door: the bootstrap runs on the host now, not as a container on qits-net.
                  #
                  # The SECOND published port on the host, and the only one that is not the edge's. It is
                  # published for docker, not for people: the same service is reachable through the edge at
                  # /artifacts like every other route.
                  - "127.0.0.1:${REGISTRY_PORT}:8080"
                environment:
                  QUARKUS_DATASOURCE_ARTIFACTS_JDBC_URL: jdbc:h2:file:/data/artifacts/h2/artifacts
                  QITS_ARTIFACTS_BLOBS_DIR: /data/artifacts/blobs
                  # Where the git host's post-receive hook delivers. Fire-and-forget: wrong host = CI
                  # silently never runs.
                  QITS_CI_INTAKE_URL: http://${ENV_NAME}-qits-ci:8080/ci/api/events/post-receive
                  # The default branch's escape hatch: a push carrying -o qits.token=<this> is let through
                  # even when protection is on. Unset would mean no value matches and nothing overrides —
                  # which is the shipped default everywhere else, and which this bootstrap cannot live with
                  # (it pushes main many times before a release endpoint exists to go through).
                  QITS_REPOSITORIES_GIT_PUSH_TOKEN: "${PUSH_TOKEN}"
                  # Protection stays ON here too: the bootstrap's own pushes carry the token above, and a
                  # rerun that silently disarmed the seatbelt would be the quiet failure.
                  QITS_REPOSITORIES_GIT_PROTECT_DEFAULT_BRANCH: "true"
                  # Machine auth. Inbound: the admin writes under /artifacts/api demand a bearer addressed to
                  # qits-platform-artifacts. Outbound: the git host's post-receive announcement to qits-ci
                  # carries one. This service's audience needs no override — it is a platform service, so its
                  # wire alias IS its repository name, which is what the image already ships.
                  QITS_AUTH_MACHINE_REQUIRED: "${MACHINE_REQUIRED}"
                  QUARKUS_OIDC_AUTH_SERVER_URL: ${IDP}
                  # The outbound switch, and the secret it must never travel without. The service names the
                  # secret QITS_ARTIFACTS_CLIENT_SECRET in its own application.properties — the canonical
                  # QUARKUS_OIDC_CLIENT_CREDENTIALS_SECRET would override it too, but one spelling is enough
                  # and the file's own is the one that documents itself.
                  QUARKUS_OIDC_CLIENT_CLIENT_ENABLED: "${MACHINE_CLIENT}"
                  QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL: ${IDP}
                  # WHO THE OUTBOUND TOKEN IS FOR. The git host announces every push to ci's intake, and
                  # ci's identity is this tier's alias — the image asks for the unqualified qits-ci, which
                  # the idp answers invalid_target because no client may request an audience that does not
                  # exist. The client id needs no line: this is a platform service, so the shipped
                  # qits-platform-artifacts is already the alias.
                  QUARKUS_OIDC_CLIENT_GRANT_OPTIONS_CLIENT_AUDIENCE: ${ENV_NAME}-qits-ci
                  QITS_ARTIFACTS_CLIENT_SECRET: "${IDP_SECRET_PLATFORM_ARTIFACTS}"
                  QITS_OBSERVABILITY_URL: http://${ENV_NAME}-qits-observability:8080
                volumes:
                  - qits-platform-artifacts-data:/data
                networks: [qits-net]
                restart: unless-stopped

              ${ENV_NAME}-qits-ci:
                image: qits/ci:latest
                container_name: ${ENV_NAME}-qits-ci
                # Unprivileged uid stays; the socket group is all it needs.
                group_add: ["${DOCKER_GID}"]
                environment:
                  QUARKUS_DATASOURCE_CI_JDBC_URL: "jdbc:h2:file:/data/ci/h2/ci;DB_CLOSE_DELAY=-1"
                  # The eventstream library (the outbox) owns its own datasource, whose shipped default sits
                  # under ${user.home} — which a container has not got, so H2 refuses the url at Flyway and the
                  # binary dies at boot. Every deployment of ci must spell this twin; so must the seed.
                  QUARKUS_DATASOURCE_EVENTSTREAM_JDBC_URL: jdbc:h2:file:/data/eventstream/h2/eventstream
                  # ci's own fetch of the pushed ref, and the same base as seen from inside a step
                  # container — steps join qits-net, so both resolve the git host directly.
                  QITS_CI_GIT_HOST_URL: http://qits-platform-artifacts:8080/artifacts
                  QITS_CI_CONTAINER_GIT_URL: http://qits-platform-artifacts:8080/artifacts
                  # The network step containers join. Still qits-net: it is the deployer's legacy network,
                  # the one every container on this host is on whatever plane it belongs to.
                  QITS_CI_NETWORK: qits-net
                  # Where a green build is announced. Fire-and-forget and swallowed at debug, so a wrong
                  # value here deploys nothing and says nothing — which is exactly why it is spelled rather
                  # than inherited. The key is qits.platform.deployments.intake-url; the
                  # qits.cd.intake-url it replaced is gone rather than aliased.
                  QITS_PLATFORM_DEPLOYMENTS_INTAKE_URL: http://${ENV_NAME}-qits-deployments:8080/platform-deployments/api/events/build-succeeded
                  # Injected into publish steps as QITS_REGISTRY: dialled by the HOST daemon (see the
                  # qits-platform-artifacts ports note).
                  QITS_ARTIFACTS_REGISTRY_HOST: localhost:${REGISTRY_PORT}
                  # The npm roots (QITS_NPM_REGISTRY_URL / QITS_NPM_PROXY_URL) are deliberately NOT overridden
                  # here: a step container dials THOSE itself, on qits-net, so ci's shipped defaults are
                  # already right. Copying the localhost mapping above onto them would point every npm install
                  # at the step container's own loopback.
                  # The websocket a step container's daemon dials BACK to this service. The image ships the
                  # unqualified ws://qits-ci:8080/ci/daemon, and nothing by that alias exists any more — a
                  # blank here fails every step with "could not reach qits-ci", which is exactly how it was
                  # found on the first prod bootstrap.
                  QITS_CI_CONTAINER_DAEMON_URL: ws://${ENV_NAME}-qits-ci:8080/ci/daemon
                  # Same class of self-name: the release train asks workspaces for version identity.
                  QITS_CI_WORKSPACES_URL: http://${ENV_NAME}-qits-workspaces:8080
                  # The binary every step container downloads and execs — uploaded by this bootstrap, digest
                  # pinned. Blank would mean every run fails as never-registered.
                  QITS_CI_DAEMON_VERSION: "${DAEMON_SHA}"
                  # Machine auth. Inbound: /ci/api/events/* demands a bearer addressed to this service whose
                  # project claim covers the event's repo. Outbound: the build-succeeded notify to the
                  # deployer carries one.
                  #
                  # THE AUDIENCE IS ITS WIRE ALIAS AND HAS TO BE SPELLED, for the same reason the deployer's
                  # is: the image ships the unqualified qits-ci, and the idp mints ${ENV_NAME}-qits-ci.
                  QITS_AUTH_MACHINE_AUDIENCE: ${ENV_NAME}-qits-ci
                  QITS_AUTH_MACHINE_REQUIRED: "${MACHINE_REQUIRED}"
                  QUARKUS_OIDC_AUTH_SERVER_URL: ${IDP}
                  QUARKUS_OIDC_CLIENT_CLIENT_ENABLED: "${MACHINE_CLIENT}"
                  QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL: ${IDP}
                  # The client id and the audience it asks for are BOTH this tier's aliases, and the image
                  # ships the unqualified pair (qits-ci asking for qits-platform-deployments). Either one
                  # left alone is a token request the idp refuses — invalid_client for the first,
                  # invalid_target for the second — on a notify that is swallowed at debug.
                  QUARKUS_OIDC_CLIENT_CLIENT_ID: ${ENV_NAME}-qits-ci
                  QUARKUS_OIDC_CLIENT_GRANT_OPTIONS_CLIENT_AUDIENCE: ${ENV_NAME}-qits-deployments
                  QUARKUS_OIDC_CLIENT_CREDENTIALS_SECRET: "${IDP_SECRET_CI}"
                  QITS_OBSERVABILITY_URL: http://${ENV_NAME}-qits-observability:8080
                volumes:
                  - qits-ci-data:/data
                  - /var/run/docker.sock:/var/run/docker.sock
                networks: [qits-net]
                restart: unless-stopped
            """;

    private static final String RUN_ARGS = """
            # Generated by qits-cli-bootstrap — qits.platform.deployments.run-args.<application>: what each deployed container
            # needs beyond its image. Whitespace-split, appended verbatim between the deployer's flags and the
            # image. The namespace was qits.cd.run-args before the merge-back; a deployment carrying the old
            # spelling configures nothing.
            #
            # An <application> is a REPOSITORY NAME, and six of them were renamed on 2026-08-08: a line under
            # a retired name configures nothing and the deployment comes up with no volumes and no env, which
            # is a container that boots, passes health and has lost its database.
            #
            # Every hostname in every value below is a WIRE ALIAS: ${ENV_NAME}-qits-<app> for a service of
            # this environment, the bare repository name for one of the four platform services.
            #
            # EVERY LINE CARRIES QITS_OBSERVABILITY_URL, for the same reason the seed compose spells it on
            # every service: the images ship the bare qits-observability, and that name died with the
            # 2026-08-08 rename. An OTLP exporter dialling a name that does not resolve drops every trace
            # and every log AND retries, so the platform goes dark while each container fills its own log
            # with the attempts.
            #
            # THE HOST PORT IS THE EDGE'S. qits-gateway carries no -p at all any more; publishing it from two
            # applications is a bind conflict that only shows up on the second cutover.
            qits.platform.deployments.run-args.qits-platform-edge=-p ${PORT}:8080 -e QITS_EDGE_ENVIRONMENTS=${ENV_NAME} -e QITS_EDGE_DEFAULT_ENVIRONMENT=${ENV_NAME} -e QITS_EDGE_UPSTREAM_HOST_PATTERN={env}-qits-gateway -e QITS_EDGE_UPSTREAM_PORT=8080 -e QITS_OBSERVABILITY_URL=http://${ENV_NAME}-qits-observability:8080
            qits.platform.deployments.run-args.qits-gateway=-e QITS_GATEWAY_PROXY_HOSTS_ARTIFACTS=qits-platform-artifacts -e QITS_GATEWAY_PROXY_HOSTS_CI=${ENV_NAME}-qits-ci -e QITS_GATEWAY_PROXY_HOSTS_PLATFORM_DEPLOYMENTS=${ENV_NAME}-qits-deployments -e QITS_GATEWAY_PROXY_HOSTS_OBSERVABILITY=${ENV_NAME}-qits-observability -e QITS_GATEWAY_PROXY_HOSTS_PROJECTS=${ENV_NAME}-qits-projects -e QITS_GATEWAY_PROXY_HOSTS_WORKSPACES=${ENV_NAME}-qits-workspaces -e QITS_GATEWAY_PROXY_HOSTS_STT=${ENV_NAME}-qits-stt -e QITS_GATEWAY_PROXY_HOSTS_EVENTS=${ENV_NAME}-qits-events -e QITS_GATEWAY_PROXY_HOSTS_PLATFORM_DOCS=qits-platform-docs -e QITS_OBSERVABILITY_URL=http://${ENV_NAME}-qits-observability:8080
            # The push token rides here so it is already in place when the default branch's protection is
            # switched on: turning protection on is then one property on the artifacts side, not a two-part
            # change that could leave a running platform locked out of its own bootstrap.
            # No QITS_AUTH_MACHINE_AUDIENCE: this is a platform service, so its wire alias is its repository
            # name and the image's own default is already that.
            # The two GC pin sources. The image ships pre-rename names, and a pin source that cannot be
            # reached makes the sweep abort fail-closed rather than delete a live artifact — so every sweep
            # stops and the cleanup banner hangs on its timeout instead.
            # The two qits-projects dials. Both images default to a monolith-era localhost, which in a
            # standalone deployment means the service calls ITSELF and the call is swallowed:
            #   QITS_PROJECTS_INTAKE_URL     every push is announced here, and that announcement is what
            #                                triggers the repository's backup. Wrong value = no backups,
            #                                reported nowhere.
            #   QITS_PROJECTS_NAME_RESOLVER_URL  turns (projectId, repoName) into a repo id, which is what
            #                                makes the name-addressed git scheme
            #                                /artifacts/git/<projectId>/<repoName> serve instead of 404.
            #                                The project agent clones itself through that scheme, so unset
            #                                means an agent container with an empty /workspace. The PATH is
            #                                qits-projects'; only the host is a deployment decision.
            qits.platform.deployments.run-args.qits-platform-artifacts=-p 127.0.0.1:${REGISTRY_PORT}:8080 -v qits-platform-artifacts-data:/data -e QUARKUS_DATASOURCE_ARTIFACTS_JDBC_URL=jdbc:h2:file:/data/artifacts/h2/artifacts -e QITS_ARTIFACTS_BLOBS_DIR=/data/artifacts/blobs -e QITS_CI_INTAKE_URL=http://${ENV_NAME}-qits-ci:8080/ci/api/events/post-receive -e QITS_PROJECTS_INTAKE_URL=http://${ENV_NAME}-qits-projects:8080/projects/api/events/post-receive -e QITS_PROJECTS_NAME_RESOLVER_URL=http://${ENV_NAME}-qits-projects:8080/projects/api/projects -e QITS_REPOSITORIES_GIT_PUSH_TOKEN=${PUSH_TOKEN} -e QITS_REPOSITORIES_GIT_PROTECT_DEFAULT_BRANCH=true -e QITS_AUTH_MACHINE_REQUIRED=${MACHINE_REQUIRED} -e QUARKUS_OIDC_AUTH_SERVER_URL=${IDP} -e QUARKUS_OIDC_CLIENT_CLIENT_ENABLED=${MACHINE_CLIENT} -e QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL=${IDP} -e QUARKUS_OIDC_CLIENT_GRANT_OPTIONS_CLIENT_AUDIENCE=${ENV_NAME}-qits-ci -e QITS_ARTIFACTS_CLIENT_SECRET=${IDP_SECRET_PLATFORM_ARTIFACTS} -e QITS_ARTIFACTS_GC_PINS_CD_BASE_URL=http://${ENV_NAME}-qits-deployments:8080/platform-deployments/api -e QITS_ARTIFACTS_GC_PINS_CI_BASE_URL=http://${ENV_NAME}-qits-ci:8080/ci/api -e QITS_OBSERVABILITY_URL=http://${ENV_NAME}-qits-observability:8080
            # QITS_PLATFORM_DEPLOYMENTS_INTAKE_URL is where a green build is announced. The notify is
            # fire-and-forget and swallowed at debug, so a wrong value deploys nothing and reports nothing.
            # QITS_AUTH_MACHINE_AUDIENCE and QUARKUS_OIDC_CLIENT_CLIENT_ID are both this tier's alias: ci
            # ships the unqualified qits-ci for each, and the idp knows neither name.
            qits.platform.deployments.run-args.qits-ci=-v qits-ci-data:/data -v /var/run/docker.sock:/var/run/docker.sock --group-add ${DOCKER_GID} -e QUARKUS_DATASOURCE_CI_JDBC_URL=jdbc:h2:file:/data/ci/h2/ci;DB_CLOSE_DELAY=-1 -e QUARKUS_DATASOURCE_EVENTSTREAM_JDBC_URL=jdbc:h2:file:/data/eventstream/h2/eventstream -e QITS_CI_GIT_HOST_URL=http://qits-platform-artifacts:8080/artifacts -e QITS_CI_CONTAINER_GIT_URL=http://qits-platform-artifacts:8080/artifacts -e QITS_CI_NETWORK=qits-net -e QITS_PLATFORM_DEPLOYMENTS_INTAKE_URL=http://${ENV_NAME}-qits-deployments:8080/platform-deployments/api/events/build-succeeded -e QITS_ARTIFACTS_REGISTRY_HOST=localhost:${REGISTRY_PORT} -e QITS_CI_DAEMON_VERSION=${DAEMON_SHA} -e QITS_CI_CONTAINER_DAEMON_URL=ws://${ENV_NAME}-qits-ci:8080/ci/daemon -e QITS_CI_WORKSPACES_URL=http://${ENV_NAME}-qits-workspaces:8080 -e QITS_EVENTS_URL=http://${ENV_NAME}-qits-events:8080 -e QITS_AUTH_MACHINE_AUDIENCE=${ENV_NAME}-qits-ci -e QITS_AUTH_MACHINE_REQUIRED=${MACHINE_REQUIRED} -e QUARKUS_OIDC_AUTH_SERVER_URL=${IDP} -e QUARKUS_OIDC_CLIENT_CLIENT_ENABLED=${MACHINE_CLIENT} -e QUARKUS_OIDC_CLIENT_AUTH_SERVER_URL=${IDP} -e QUARKUS_OIDC_CLIENT_CLIENT_ID=${ENV_NAME}-qits-ci -e QUARKUS_OIDC_CLIENT_GRANT_OPTIONS_CLIENT_AUDIENCE=${ENV_NAME}-qits-deployments -e QUARKUS_OIDC_CLIENT_CREDENTIALS_SECRET=${IDP_SECRET_CI} -e QITS_OBSERVABILITY_URL=http://${ENV_NAME}-qits-observability:8080
            # The deployer's own deployment — the self-update handoff. Three mounts, all load-bearing: the
            # data volume holds the topology AND the deployment history, the config volume holds this very
            # file so the successor inherits every line of it, and the docker socket is what makes it a
            # deployer at all. Machine auth INBOUND only: it validates qits-ci's bearer and mints nothing, so
            # no oidc-client and no secret — but the audience it validates AGAINST is this tier's alias, and
            # the image still ships the pre-rename repository name.
            qits.platform.deployments.run-args.qits-deployments=-v qits-deployments-data:/data -v qits-deployments-config:/work/config -v /var/run/docker.sock:/var/run/docker.sock --group-add ${DOCKER_GID} -e QUARKUS_DATASOURCE_PLATFORMDEPLOYMENTS_JDBC_URL=jdbc:h2:file:/data/platformdeployments/h2/platformdeployments -e QITS_ARTIFACTS_REGISTRY_HOST=localhost:${REGISTRY_PORT} -e QITS_AUTH_MACHINE_AUDIENCE=${ENV_NAME}-qits-deployments -e QITS_AUTH_MACHINE_REQUIRED=${MACHINE_REQUIRED} -e QUARKUS_OIDC_AUTH_SERVER_URL=${IDP} -e QITS_OBSERVABILITY_URL=http://${ENV_NAME}-qits-observability:8080
            # The idp's own deployment. The volume is the whole point: the signing key is in that database, and
            # a redeploy that lands on a fresh one invalidates every token in flight. The claims grant is the
            # git host's wildcard — it announces pushes for every repo, so its project claim covers every value.
            # QITS_IDP_CLIENTS and both audience lists are restated in full, because each key REPLACES the
            # shipped list rather than extending it — and every id in them is a wire alias, so they move with
            # the environment name while the image's defaults cannot.
            qits.platform.deployments.run-args.qits-platform-idp=-v qits-platform-idp-data:/data -e QUARKUS_DATASOURCE_IDP_JDBC_URL=jdbc:h2:file:/data/idp/h2/idp -e QITS_IDP_ISSUER=${IDP} -e QITS_IDP_CLIENTS=${IDP_CLIENTS} -e QITS_IDP_CLIENT_${ENV_KEY}_QITS_CI_SECRET=${IDP_SECRET_CI} -e QITS_IDP_CLIENT_QITS_PLATFORM_ARTIFACTS_SECRET=${IDP_SECRET_PLATFORM_ARTIFACTS} -e QITS_IDP_CLIENT_${ENV_KEY}_QITS_WORKSPACES_SECRET=${IDP_SECRET_WORKSPACES} -e QITS_IDP_CLIENT_${ENV_KEY}_QITS_GATEWAY_SECRET=${IDP_SECRET_GATEWAY} -e QITS_IDP_CLIENT_${ENV_KEY}_QITS_CI_AUDIENCES=${IDP_AUDIENCES} -e QITS_IDP_CLIENT_QITS_PLATFORM_ARTIFACTS_AUDIENCES=${IDP_AUDIENCES} -e QITS_IDP_CLIENT_QITS_PLATFORM_ARTIFACTS_CLAIMS_PROJECT=* -e QITS_OBSERVABILITY_URL=http://${ENV_NAME}-qits-observability:8080
            qits.platform.deployments.run-args.qits-stt=-v qits-stt-data:/data -e QITS_SPEECH_HOME=/data/speech -e QITS_OBSERVABILITY_URL=http://${ENV_NAME}-qits-observability:8080
            # projects no longer mounts the shared repositories volume at all — it clones its own git mirrors
            # over the wire, through qits.artifacts.url, into its own data dir. QITS_PROJECTS_DATA_DIR is
            # spelled here rather than left to the image default (${user.home}/...), which resolves to the
            # literal "?" under this image's passwd-less UID 1001 — the same reason the datasource URLs are
            # spelled.
            #
            # QITS_REPOSITORIES_GIT_PUSH_TOKEN is the SAME token qits-platform-artifacts' hook checks, one
            # line above. projects advances refs on the git host by pushing now, and the default branch is
            # protected here, so without the token every pull that fast-forwards main is refused. A branch
            # delete deliberately sends no token.
            #
            # QITS_PROJECTS_AGENT_IMAGE names the image a project agent container runs. The shipped
            # default is qits/project-agent:latest; this platform builds the tag :native, so the name
            # is spelled here rather than left to drift from what exists on the host.
            #
            # The docker socket, on the same terms qits-ci and qits-workspaces have it: DockerAgentRuntime
            # shells `docker run` to create a project's agent container, so without the socket every agent
            # start fails at the runtime rather than at a config check. The mount hands this container
            # control of the host daemon, which is root-equivalent — the service's own docs call supplying
            # it a deliberate deployment act rather than an image default, and this line IS that act.
            #
            # QITS_PROJECTS_OWN_HOST and QITS_PROJECTS_AGENT_GIT_BASE are the two addresses an agent
            # container is handed at creation: this service's own wire name, and the git host it clones
            # from. The image ships pre-rename defaults (qits-projects, qits-artifacts), which resolve to
            # nothing on this platform, so a container created from them never dials back and its boot
            # clone fails. Both are spelled here, the first with the environment's own prefix.
            qits.platform.deployments.run-args.qits-projects=-v qits-projects-data:/data -v /var/run/docker.sock:/var/run/docker.sock --group-add ${DOCKER_GID} -e QUARKUS_DATASOURCE_PROJECTS_JDBC_URL=jdbc:h2:file:/data/projects/h2/projects -e QUARKUS_DATASOURCE_EPICS_JDBC_URL=jdbc:h2:file:/data/epics/h2/epics -e QITS_PROJECTS_DATA_DIR=/data/mirrors -e QITS_ARTIFACTS_URL=http://qits-platform-artifacts:8080 -e QITS_REPOSITORIES_GIT_PUSH_TOKEN=${PUSH_TOKEN} -e QITS_PROJECTS_AGENT_IMAGE=qits/project-agent:native -e QITS_PROJECTS_OWN_HOST=${ENV_NAME}-qits-projects -e QITS_PROJECTS_AGENT_GIT_BASE=http://qits-platform-artifacts:8080/artifacts/git -e QITS_OBSERVABILITY_URL=http://${ENV_NAME}-qits-observability:8080
            # QITS_ARTIFACTS_URL is where release PUSHES the release commit — the git host, over HTTP, so
            # the ordinary post-receive fires and the ordinary pipeline builds it.
            # The eventstream twin (same pair qits-ci carries above): a release publishes SoftwareRelease
            # through the shared bus client, whose outbox owns its own datasource. QITS_EVENTS_URL is where
            # the outbox drains to.
            # QITS_WORKSPACE_GIT_HOST (qits.workspace.git-host) is the address a WORKSPACE container uses to
            # reach this platform — git clone/push, OTLP, the agent's MCP servers and the daemon control
            # socket are all composed as http://<this>:8080/... It must be spelled, because the sentinel
            # "auto" is wrong on this topology and wrong silently: auto detects WSL2 and answers the primary
            # LAN IPv4, which is the address of the machine when qits runs ON the host — but qits-workspaces
            # runs in a container here, so what it measures is its OWN container's address and every
            # container->platform URL 404s. The gateway, not qits-workspaces or the artifacts service: it is
            # the one name on qits-net that fronts a WHOLE environment. Not the edge either — a workspace
            # belongs to a tier, and the gateway is the tier's own front door, while the edge exists to pick
            # between tiers for traffic that arrived from outside.
            qits.platform.deployments.run-args.qits-workspaces=-v qits-workspaces-data:/data -v /var/run/docker.sock:/var/run/docker.sock --group-add ${DOCKER_GID} -e QUARKUS_DATASOURCE_WORKSPACES_JDBC_URL=jdbc:h2:file:/data/workspaces/h2/workspaces -e QUARKUS_DATASOURCE_EVENTSTREAM_JDBC_URL=jdbc:h2:file:/data/eventstream/h2/eventstream -e QITS_PROJECTS_URL=http://${ENV_NAME}-qits-projects:8080 -e QITS_ARTIFACTS_URL=http://qits-platform-artifacts:8080 -e QITS_EVENTS_URL=http://${ENV_NAME}-qits-events:8080 -e QITS_WORKSPACE_GIT_HOST=${ENV_NAME}-qits-gateway -e QITS_OBSERVABILITY_URL=http://${ENV_NAME}-qits-observability:8080
            # The reading surface over qits-platform-artifacts' docs repository. ONE line and no volume,
            # because this service stores nothing — `latest` is a query over the store's rows rather
            # than a pointer it holds, so a redeploy loses nothing and there is no datasource URL to
            # spell. The address equals the service's own shipped default and is spelled anyway, for
            # the reason qits-projects' QITS_ARTIFACTS_URL is: an address a deployment inherits
            # silently is an address nobody knows to change. It is the SAME value qits-ci injects
            # into a publishing step as $QITS_DOCS_URL, so the publisher and the reader cannot
            # disagree about where documentation lives.
            qits.platform.deployments.run-args.qits-platform-docs=-e QITS_PLATFORM_DOCS_ARTIFACTS_URL=http://qits-platform-artifacts:8080/artifacts/docs/docs -e QITS_OBSERVABILITY_URL=http://${ENV_NAME}-qits-observability:8080
            qits.platform.deployments.run-args.qits-events=-v qits-events-data:/data -e QUARKUS_DATASOURCE_EVENTS_JDBC_URL=jdbc:h2:file:/data/events/h2/events -e QITS_OBSERVABILITY_URL=http://${ENV_NAME}-qits-observability:8080
            # The receiver's own telemetry, addressed to itself. That is the consistent answer rather than
            # the clever one: qits-observability is an ordinary OTLP client like every application above,
            # and leaving it on the dead default would keep exactly one container spamming retries. This
            # application needed nothing beyond its image until the address had to be spelled, which is why
            # it had no line at all.
            qits.platform.deployments.run-args.qits-observability=-e QITS_OBSERVABILITY_URL=http://${ENV_NAME}-qits-observability:8080
            """;
}
